### ISSUE TITLE
After importing Sklearn ,  AttributeError: module 'numpy' has no attribute '_no_nep50_warning'

### ISSUE THREAD

**Issue by vinny2393** [numpy/numpy#23570]
### Steps to reproduce:

I am getting a Numpy error while importing sklearn  this issue just after creating new environment in the anaconda , I just installed Tensorflow, pandas, numpy , plotlty scikit learn.

### Error message:

```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[18], line 5
      2 import numpy as np
      4 #from sklearn.preprocessing import StandardScaler
----> 5 import sklearn
      7 import plotly.graph_objects as go

File ~/anaconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/__init__.py:82
     80 from . import _distributor_init  # noqa: F401
     81 from . import __check_build  # noqa: F401
---> 82 from .base import clone
     83 from .utils._show_versions import show_versions
     85 __all__ = [
     86     "calibration",
     87     "cluster",
   (...)
    128     "show_versions",
    129 ]

File ~/anaconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/base.py:17
     15 from . import __version__
     16 from ._config import get_config
---> 17 from .utils import _IS_32BIT
     18 from .utils._tags import (
     19     _DEFAULT_TAGS,
     20     _safe_tags,
     21 )
     22 from .utils.validation import check_X_y

File ~/anaconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/utils/__init__.py:28
     26 from ..exceptions import DataConversionWarning
     27 from .deprecation import deprecated
---> 28 from .fixes import np_version, parse_version
     29 from ._estimator_html_repr import estimator_html_repr
     30 from .validation import (
     31     as_float_array,
     32     assert_all_finite,
   (...)
     40     check_scalar,
     41 )

File ~/anaconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/utils/fixes.py:20
     18 import scipy.sparse as sp
     19 import scipy
---> 20 import scipy.stats
     21 from scipy.sparse.linalg import lsqr as sparse_lsqr  # noqa
     22 import threadpoolctl

File ~/anaconda3/envs/tensorflow/lib/python3.10/site-packages/scipy/stats/__init__.py:485
      1 """
      2 .. _statsrefmanual:
      3 
   (...)
    480 
    481 """
    483 from ._warnings_errors import (ConstantInputWarning, NearConstantInputWarning,
    484                                DegenerateDataWarning, FitError)
--> 485 from ._stats_py import *
    486 from ._variation import variation
    487 from .distributions import *

File ~/anaconda3/envs/tensorflow/lib/python3.10/site-packages/scipy/stats/_stats_py.py:37
     35 from numpy import array, asarray, ma
     36 from numpy.lib import NumpyVersion
---> 37 from numpy.testing import suppress_warnings
     39 from scipy.spatial.distance import cdist
     40 from scipy.ndimage import _measurements

File ~/anaconda3/envs/tensorflow/lib/python3.10/site-packages/numpy/testing/__init__.py:11
      8 from unittest import TestCase
     10 from . import _private
---> 11 from ._private.utils import *
     12 from ._private.utils import (_assert_valid_refcount, _gen_alignment_data)
     13 from ._private import extbuild, decorators as dec

File ~/anaconda3/envs/tensorflow/lib/python3.10/site-packages/numpy/testing/_private/utils.py:480
    476         pprint.pprint(desired, msg)
    477         raise AssertionError(msg.getvalue())
--> 480 @np._no_nep50_warning()
    481 def assert_almost_equal(actual,desired,decimal=7,err_msg='',verbose=True):
    482     """
    483     Raises an AssertionError if two items are not equal up to desired
    484     precision.
   (...)
    548 
    549     """
    550     __tracebackhide__ = True  # Hide traceback for py.test

File ~/anaconda3/envs/tensorflow/lib/python3.10/site-packages/numpy/__init__.py:311, in __getattr__(attr)
    304 if attr in __former_attrs__:
    305     raise AttributeError(__former_attrs__[attr])
    307 # Importing Tester requires importing all of UnitTest which is not a
    308 # cheap import Since it is mainly used in test suits, we lazy import it
    309 # here to save on the order of 10 ms of import time for most users
    310 #
--> 311 # The previous way Tester was imported also had a side effect of adding
    312 # the full `numpy.testing` namespace
    313 if attr == 'testing':
    314     import numpy.testing as testing

AttributeError: module 'numpy' has no attribute '_no_nep50_warning'
```

**Comment by andyfaff** [comment]
What numpy version are you using, how did you install numpy, what OS are you using?

FWIW the import that's being used here works on `1.24.2`.

**Comment by vinny2393** [comment]
Well I Am using 
OS: MAC OS
Numpy Version: 1.24.2
Installation :  In anaconda,  using conda installation

**Comment by andyfaff** [comment]
Arm64 or x86_64?

**Comment by vinny2393** [comment]
Yes

**Comment by vinny2393** [comment]
Arm64 or x86_64?  MAC OS M1 chip

**Comment by vinny2393** [comment]
The problem is with Python version  3.10 and sklearn . So if you think  its resolve, you can close it @andyfaff

**Comment by vinny2393** [comment]
I think that could be a problem.

**Comment by djpruneda** [comment]
Just in case it helps, I got this error message after installing the ydata_profiling module, which uninstalled and then reinstalled the numpy package. 

The solution that worked for me was to restart the kernel

I'm using Python 3.11 with Anaconda on a Win 11 x86 PC

**Comment by kybuno** [comment]
restarting the kernel helped fix it for me too!

i just installed numpy, scipy and gensim and immediately tried to run the jupyter cell. 
got the error AttributeError: module 'numpy' has no attribute '_no_nep50_warning'

after restarting kernel, no issue anymore 👍
