### PR TITLE
TYP: Backport typing fixes

### LINKED ISSUE #29203: TYP: typehints for __array__
### Describe the issue:

I have a class that has an numpy array as an attribute. Its `__array__` method simply calls `np.ndarray.__array__` (see below). Mypy complains about non-matching types, but I believe the typehints that I provide are reasonable.

### Reproduce the code example:

```python
import numpy as np
import numpy.typing as npt
from typing import Optional

class Test:

    def __init__(self, ar: np.ndarray):
        self.ar = ar

    def __array__(self,
                  dtype: Optional[npt.DTypeLike] = None,
                  *,
                  copy: Optional[bool] = None) -> np.ndarray:
        return self.ar.__array__(dtype,copy=copy)
```

### Error message:

```shell
test.py:14: error: Argument 1 to "__array__" of "ndarray" has incompatible type "type[Any] | dtype[Any] | _SupportsDType[dtype[Any]] | tuple[Any, Any] | list[Any] | _DTypeDict | str | None | None"; expected "None"  [arg-type]
test.py:14: error: Argument "copy" to "__array__" of "ndarray" has incompatible type "builtins.bool | None"; expected "numpy.bool[builtins.bool] | None"  [arg-type]
```

### Python and NumPy Versions:

- Python 3.13.3
- NumPy 2.3.0

### Type-checker version and settings:

- Mypy 1.16.0

### Additional typing packages.

n/a

### LINKED ISSUE #29214: TYP: incorrect type inference for iteration elements? (numpy 2.3.0)
### Describe the issue:

When updating from numpy 2.2.6 to 2.3.0, I encountered a new type check error that I believe is incorrect.

When you iterate over a matrix, the elements should be the same shape as the original matrix, but with one dimension dropped. Because the `NDArray` type has ambiguous shape, elements could either be **an array OR a scalar**.

However, in numpy 2.3.0, when I iterate over a matrix of type `NDArray[np.float64]`, numpy typing says each element has type `np.float64`. It is assuming that the matrix is 1-dimensional and each element is a scalar, which is incorrect.

```py
arr: NDArray[np.float64] = np.zeros((5,3))
for element in arr:
  # Each `element` is an `NDArray[np.float64]` of shape (3)
  # But instead, numpy typing says it is a `float64`
```

In numpy 2.2.6, each element had type `Any` - vague, but at least not incorrect.

---

From the release notes, I see that improvements were made to numpy's static typing in 2.3.0. I also see `mypy_plugin` was deprecated, but I don't think that's the issue because I didn't have the plugin enabled in the first place.

So is this an actual bug, or am I misunderstanding how to use static typing with numpy? I feel a little shaky on the subject. If I am doing this wrong, please show me the correct way 🙏 

### Reproduce the code example:

```python
"""A simple example that should throw a type check error."""

import numpy as np
from numpy.typing import NDArray


def example(pixels: NDArray[np.float64]) -> None:
	"""`pixels` is an NDArray of shape (length, 3)."""
	# Convert NDArray to a list of tuples
	tuples: list[tuple] = [tuple(pixel) for pixel in pixels]
```

### Error message:

```shell
error: Argument 1 to "tuple" has incompatible type "float64"; expected "Iterable[Any]"  [arg-type]
```

### Python and NumPy Versions:

```
2.3.0
3.13.5 (main, Jun 12 2025, 22:47:08) [GCC 12.2.0]
```

### Type-checker version and settings:

mypy version: 1.16.1
mypy command: `mypy .`

### Additional typing packages.

_No response_

### PR DESCRIPTION
**Pull request by charris**
Backports:

#29218
- TYP: Workaround for a mypy issue in ndarray.__iter__ 
  Closes #29214

  ---

  The workaround I had in mind was also bugged, so I suppose that'd make it a workaroundaround.
  And just like that   term, this workaroundaround itself also looks pretty absurd.

#29204
- TYP: fix ndarray.__array__ annotation for copy
  closes https://github.com/numpy/numpy/issues/29203

### CODE REVIEW

**Comment by jorenham** [comment]
The ruff config from https://github.com/numpy/numpy/pull/29183 changes are probably to blame for the circleci failure
