### ISSUE TITLE
BUG: Error running `spin mypy` from the repository folder

### ISSUE THREAD

**Issue by Andrej730** [numpy/numpy#26816]
### Describe the issue:

If you try to run `spin mypy` from the `numpy` repository folder it fails with `ImportError: cannot import name 'version' from partially initialized module 'numpy' (most likely due to a circular import) (\numpy\numpy\__init__.py)` since it's trying to import `numpy` from the repository folder instead of `\numpy\build-install\usr\Lib\site-packages`.

`-P` flag should prevent that as it does in `$ '\Python311\python.exe' -P -c 'import numpy'`
But `pytest` seem to ignore it since it fails on `$ '\Python311\python.exe' -P -m pytest 'numpy\typing'`.

### Reproduce the code example:

```python
>spin mypy

Invoking `build` prior to running tests:
$ '\Python311\python.exe' vendored-meson/meson/meson.py compile -C build
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: \Python311\Scripts\ninja.EXE -C /numpy/build
ninja: Entering directory `/numpy/build'
[1/1] Generating numpy/generate-version with a custom command
Saving version to numpy\version.py
$ '\Python311\python.exe' vendored-meson/meson/meson.py install --only-changed -C build --destdir ../build-install
$ export PYTHONPATH="\numpy\build-install\usr\Lib\site-packages;\Python311\Lib\placeholder_modules"
$ export PYTHONPATH="\numpy\build-install\usr\Lib\site-packages"
$ '\Python311\python.exe' -P -c 'import numpy'
$ '\Python311\python.exe' -P -m pytest 'numpy\typing'
ImportError while loading conftest '\numpy\numpy\conftest.py'.
numpy\__init__.py:97: in <module>
    from . import version
E   ImportError: cannot import name 'version' from partially initialized module 'numpy' (most likely due to a circular import) (\numpy\numpy\__init__.py)
```

### Python and NumPy Versions:

Python 3.11, 2.1.0.dev0+git20240626.389b26d

Possibly related to #26525

**Comment by ngoldbaum** [comment]
This is an issue with the current version of spin. I think @stefanv is working on a fix. For now I think installing spin 0.8 should let you get past this error.

**Comment by Andrej730** [comment]
Can confirm that it's working on spin 0.8 as it uses different pytest command: `'python.exe' -m pytest '--rootdir=\numpy\build-install\usr\Lib\site-packages' 'numpy\typing'`

**Comment by stefanv** [comment]
Could you please test with an install from main? I.e.:

pip install https://github.com/scientific-python/spin/archive/master.zip

It looks to be working for me now, and we're about to cut a new release.

**Comment by Andrej730** [comment]
> Could you please test with an install from main? I.e.:

@stefanv Can confirm that it's working too - it's now changing cwd explicitly.

```
$ cd \numpy\build-install\usr\Lib\site-packages
$ 'Python311\python.exe' -P -m pytest --import-mode=importlib 'numpy\typing'
```

**Comment by stefanv** [comment]
spin v0.11 is out: https://github.com/scientific-python/spin/releases/tag/v0.11
