### PR TITLE
BUG: Address failures in aarch64 gcc builds due to #22096

### PR DESCRIPTION
**Pull request by Developer-Ecosystem-Engineering**
gcc was unhappy with #22096 due to 

`numpy/core/src/common/simd/neon/conversion.h:93:22: error: incompatible type for argument 1 of ‘vuzp1q_u8’ 93 | return vuzp1q_u8(a, b); | ^ | | | npyv_b16 {aka uint16x8_t}
`

We cast it to resolve the rigorous type checking gcc is using.

### CODE REVIEW

**Comment by charris** [comment]
Thanks @Developer-Ecosystem-Engineering . Will need to run the wheel builds to check this.

**Comment by charris** [comment]
Looks like you missed one on line 93: https://app.travis-ci.com/github/MacPython/numpy-wheels/jobs/579571569
