### PR TITLE
DOC: wrong name in docs

### LINKED ISSUE #20926: DOC: reference to non-existing `chebfromfunction`.
### Issue with current documentation:

```
$ rg chebfromfunction
numpy/polynomial/chebyshev.py
1811:    >>> C.chebfromfunction(lambda x: np.tanh(x) + 0.5, 8)
2063:        See `numpy.polynomial.chebfromfunction` for more details.
```

The first one on line triggers an `AttributeError: module 'numpy.polynomial.chebyshev' has no attribute 'chebfromfunction'`, 

### Idea or request for content:

My guess is the author meant to use `chebinterpolate`. This was introduced in 3b8d3bd155def203da0136b223ec7fabac425337 (#9492), which renames `chebinterp` to `chebinterpolate`  and there was likely some back and forth and the naming ?

### PR DESCRIPTION
**Pull request by Carreau**
closes #20926

As using `chebinterpolate` give the same result as what is in the doc example, I assume this is what is mean.

### CODE REVIEW

**Comment by charris** [comment]
Thanks @Carreau .
