### ISSUE TITLE
Version 1.16.0 and Version 1.16.1 don't work with tensorflow==1.12 modules. Error: 'numpy.ufunc' object has no attribute '__module__'

### ISSUE THREAD

**Issue by kulkarnivishal** [numpy/numpy#12910]
The latest versions don't seem to work with tensorflow 1.12. Please find below the import statements that fail:

### Reproducing code example:

```python
import numpy as np
from tensorflow.contrib.quantize.python import graph_matcher
from tensorflow.contrib import distributions
from tensorflow.contrib.distributions.python.ops.estimator import *
from tensorflow.contrib.learn.python.learn.estimators.head import _compute_weighted_loss
from tensorflow.contrib.learn.python.learn import estimators
from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
from tensorflow.contrib.learn.python.learn.estimators import estimator
from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
import dask.dataframe as dd
```

### Error message:

AttributeError: `numpy.ufunc`
 object has no attribute `__module__`

N/A

See above code

**Comment by eric-wieser** [comment]
Please show the full traceback, and preferably reduce your example to one import statement

**Comment by kulkarnivishal** [comment]
My intention behind including these import statements is that none of these work. May be it would. I certainly find it helpful. 
Nevertheless, here's the full traceback:

 File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/contrib/__init__.py", line 49, in <module>
    from tensorflow.contrib import distributions
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/contrib/distributions/__init__.py", line 38, in <module>
    from tensorflow.contrib.distributions.python.ops.estimator import *
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/contrib/distributions/python/ops/estimator.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.head import _compute_weighted_loss
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/contrib/learn/__init__.py", line 96, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/contrib/learn/python/__init__.py", line 28, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 302, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 35, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 36, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 52, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 26, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 33, in <module>
    import dask.dataframe as dd
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/dask/dataframe/__init__.py", line 3, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/dask/dataframe/core.py", line 20, in <module>
    from .. import array as da
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/dask/array/__init__.py", line 8, in <module>
    from .routines import (take, choose, argwhere, where, coarsen, insert,
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/dask/array/routines.py", line 245, in <module>
    @wraps(np.matmul)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'numpy.ufunc' object has no attribute '__module__'

**Comment by eric-wieser** [comment]
Thanks, that traceback shows me that the crash happens in dask. That's something they already have a fix for.

You either need to update dask, or wait for their next release.

**Comment by charris** [comment]
I get
```
In [1]: numpy.__version__
Out[1]: '1.16.2.dev0+ef9a17a'

In [2]: numpy.ufunc.__module__
Out[2]: 'numpy'

In [3]: getattr(numpy.ufunc, '__module__')
Out[3]: 'numpy'

In [4]: numpy.__version__
Out[4]: '1.16.2.dev0+ef9a17a'
```
I think there is a problem with your install, you probably need a clean install of numpy, and I don't know if that is compatible with Anaconda.
