### ISSUE TITLE
NumPy does not install on Python 3.12.0b1

### ISSUE THREAD

**Issue by bersbersbers** [numpy/numpy#23808]
### Describe the issue:

Related:
https://github.com/pypa/pip/issues/11501#issuecomment-1562025923
https://github.com/pypa/setuptools/issues/3935

https://github.com/numpy/numpy/blob/cc0abd768575d7f9e862de0b4912af27f6e9690d/pyproject.toml#LL7C6-L7C16

### Reproduce the code example:

```python
pip install numpy
```

### Error message:

```shell
pip install numpy
Collecting numpy
  Using cached numpy-1.24.3.tar.gz (10.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\bers\.pyenv-win-venv\envs\project_3.12\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\bers\.pyenv-win-venv\envs\project_3.12\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\bers\.pyenv-win-venv\envs\project_3.12\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\Users\bers\.pyenv-win-venv\envs\project_3.12\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\bers\.pyenv\pyenv-win\versions\3.12.0b1\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1293, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1266, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1216, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 400, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1293, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1266, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1237, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 841, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 994, in exec_module
        File "<frozen importlib._bootstrap>", line 400, in _call_with_frames_removed
        File "C:\Users\bers\AppData\Local\Temp\pip-build-env-8dt1uf4c\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\bers\AppData\Local\Temp\pip-build-env-8dt1uf4c\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\bers\AppData\Local\Temp\pip-build-env-8dt1uf4c\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Runtime information:

Cannot install numpy :)
Python 3.12.0b1 on Windows 10 21H2

**Comment by mattip** [comment]
We deliberately pin setuptools to work around other problems with numpy.distutils. The plan for python 3.12 is to move to the meson build system, and to deprecate use of setuptools. You can try out the meson build using python3.12 -m pip install -r build_requirements.txt; python3.12 -m spin build.

**Comment by bersbersbers** [comment]
Thanks, understood!

I just came across https://numpy.org/devdocs/reference/distutils_status_migration.html, which reads

> It may be beneficial to wait with migrating until there are examples from other projects to follow

I agree in principle, but I feel that this approach may deadlock if many other projects depend on numpy :) for example, matplotlib does not install on 3.12.0b1 because it depends on numpy at build time, and then that dependency is carried further to all projects depending on matplotlib.

**Comment by mattip** [comment]
That advice could use an update, especially before the 1.25 release freezes the documentation. SciPy has migrated to meson-python, and NumPy should migrate soon. Rather than trying to get setuptools to work with python3.12, we should start testing the CPython 3.12b1 with meson.

**Comment by charris** [comment]
> That advice could use an update, especially before the 1.25 release freezes the documentation. 

Could you open an issue for that? I am going to release 1.25.0rc1 without it, but there will still be time before the final.

**Comment by mattip** [comment]
> matplotlib does not install on 3.12.0b1 because it depends on numpy at build time,

Maybe we should be uploading pre-release wheels to https://anaconda.org/scientific-python-nightly-wheels/numpy. It seems [cibuildwheel has a option for this](https://cibuildwheel.readthedocs.io/en/stable/options/#prerelease-pythons)

**Comment by rgommers** [comment]
I think now that `1.25.x` has branched, we can make the switch to Meson by default in `main`. That will make `pip install .` & co work with Python 3.12 beta's (module any crashes due to incompatibilities between CPython, NumPy and Cython of course - and we know we have one of those right now: gh-23766). WDYT?

Re uploading a nightly: let's consider it once NumPy actually passes its test suite with a CPython beta? It seems too early now, we don't even run it in our own CI yet.

**Comment by mattip** [comment]
We need SIMD testing to work to make the transition.

**Comment by rgommers** [comment]
> We need SIMD testing to work to make the transition.

That can still be done with `python setup.py install`, as is already done in `armv7_simd_test`.

**Comment by rgommers** [comment]
> I think now that `1.25.x` has branched, we can make the switch to Meson by default in `main`. That will make `pip install .` & co work with Python 3.12 beta's (module any crashes due to incompatibilities between CPython, NumPy and Cython of course

This is being done in gh-23838 - which is close, but needs working through some CI failures. Until it is merged, one can either use the branch from which I made that PR, or follow the instructions at https://github.com/numpy/numpy/blob/main/building_with_meson.md#pip-install.

Questions about this continue to come in, so I'll pin this issue.

**Comment by EwoutH** [comment]
Congratulations on getting https://github.com/numpy/numpy/pull/23838 in!

What are the next steps in Python 3.12 support?

**Comment by rgommers** [comment]
> What are the next steps in Python 3.12 support?

Uploading nightlies to https://anaconda.org/scientific-python-nightly-wheels, so other projects can use those. PR for that is up, I'll update here once they're available.

**Comment by rgommers** [comment]
Wheels for Python 312 x86-64 (macOS, Windows, manylinux and musllinux) are up on https://anaconda.org/scientific-python-nightly-wheels/numpy/files. The rest (arm64/aarch64) should land as well by tomorrow when the next scheduled wheel build on Cirrus CI runs.

**Comment by lithomas1** [comment]
Is there any recommendation for how downstream(e.g. pandas) should build Python 3.12 wheels?

We can't build with the tarball of numpy 1.25 since that uses an ancient setuptools not compatible with Python 3.12, and I don't like the sound of building wheels using a random numpy nightly.

If numpy 2.0 (or whatever the next version is) comes a couple months before Python 3.12 final, I guess it's no big deal, but if not, maybe it might be good to backport #23838

**Comment by charris** [comment]
@lithomas1 When 3.12.0rc1 comes out we will release a NumPy 1.26.

**Comment by bersbersbers** [comment]
> @lithomas1 When 3.12.0rc1 comes out we will release a NumPy 1.26.

I find this rather late TBH. From PEP 693:

> 3.12.0 candidate 1: Monday, 2023-07-31
3.12.0 candidate 2: Monday, 2023-09-04
3.12.0 final: Monday, 2023-10-02

This would mean waiting another five weeks to publicly release wheels, which is then the first point in time where many downstream developers will start even considering testing for Python 3.12 (I do not expect many to go through the pain of tracking down wheels if they are not available on PyPI). And from that point on, it's only roughly two months until the final release of 3.12.

I have always wondered how it could take months until even some popular libraries start supporting the latest Python version, and see this as a major hurdle to, as a user, installing and using the latest Python version by default. And I find that numpy, which is *very* close to the root of many Python environments' depedency tree, could be better example in this regard.

**Comment by rgommers** [comment]
@bersbersbers it's simple: the first release candidate is when CPython becomes ABI-stable, hence it's the first point where we can produce wheels that should be stable too. Any wheels produced against beta versions of CPython may start crashing at any point when a new CPython version comes out, so we will not put them on PyPI.

Whether the 2 month window is enough or not is entirely up to the Python core devs, they can extend it if they want to. The current feeling seems to be that there is no need for that.

**Comment by EwoutH** [comment]
I started a thread on discuss.python.org a while ago on these ABI tracking problems. If you have any ideas on this, please share them in [this thread](https://discuss.python.org/t/idea-tracking-abi-additions-and-changes-for-better-pre-release-wheel-management/26033)!

**Comment by jaraco** [comment]
I'm assuming this issue also tracks getting Python 3.12 builds for Windows, which may just come in the form of wheels after build issues are addressed.

**Comment by rgommers** [comment]
> I'm assuming this issue also tracks getting Python 3.12 builds for Windows, which may just come in the form of wheels after build issues are addressed.

Any OS indeed. If you need Windows wheels now for testing purposes, you can get them at https://anaconda.org/scientific-python-nightly-wheels/numpy/files.

**Comment by hugovk** [comment]
> @lithomas1 When 3.12.0rc1 comes out we will release a NumPy 1.26.

3.12.0rc1 is now out:

> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0. Any binary wheels built against Python 3.12.0rc1 will work with future versions of Python 3.12. 

https://discuss.python.org/t/python-3-12-0-release-candidate-1-released/31137?u=hugovk

**Comment by rgommers** [comment]
We're well aware. `cibuildwheel` support appeared like 3 hours ago. A numpy beta or rc will appear within the next couple of days.

**Comment by rgommers** [comment]
A pre-release is now available on PyPI: https://pypi.org/project/numpy/1.26.0b1/. You can install it with `pip install numpy --pre`. This version is guaranteed to be ABI-stable, and you can use it to build wheels for Python 3.12 against if you already want to release those for your own project.

**Comment by dketterer** [comment]
Are there any plans to backport the new buildsytem to older numpy versions? This would allow to install packages that require numpy before 1.26 with Python3.12.

**Comment by mattip** [comment]
There are no plans to backport this without a clear use case. Anyone who wants to use older numpy versions can use older python versions, no?

**Comment by henryiii** [comment]
FYI, if it's in your build-system requirements, then you can use `PIP_PRE=1`. You can also use:

```toml
[build-system]
requires = [
  'numpy; python_version<"3.12"',
  'numpy>=1.26.0b1; python_version>="3.12"',
  # ...
]
```

Though be warned distros like Fedora seem to be building older versions of NumPy with Python 3.12. I hit that already. :(

**Comment by rgommers** [comment]
Nice tips @henryiii, thanks!

> Though be warned distros like Fedora seem to be building older versions of NumPy with Python 3.12. I hit that already. :(

Yes, it's not the first time they've done this kind of thing. It's causes more problems than it solves and is quite annoying. I think it's only Fedora that's doing this - or are you aware of others?

> It seems the 2.0 nightly wheels are now the only ones on pypi.anaconda.org. Would it be possible to get the dev versions of 1.x (ex. 1.26.x) on there as well?

I don't think we want to do that - there are zero changes of interest that are not already on PyPI now, and it's extra work for us. If you need `1.26.0b1`, can you please switch your own download location to PyPI?

> I install my unstable versions from there and it seems numpy 2.0 is causing either distutils errors (scipy triggering a `__getattr__` in numpy)

That should be a temporary hiccup that'll be fixed in the SciPy nightly. 

> or just completely hanging (haven't tracked this down yet but I'm guessing Cython extension compatibility).

That sounds more worrisome. NumPy `main` does require Cython 3.0 now. If it's a SciPy hang, can you open a SciPy issue with your environment details? Please feel free to Cc me.

**Comment by neutrinoceros** [comment]
If I may add to @henryiii 's comment: `python_version >= '3.12'` doesn't match release candidates, so at the moment, I think the needed build requirements would be
```toml
[build-system]
requires = [
  'numpy; python_version<"3.12.0rc1"',
  'numpy>=1.26.0b1; python_version>="3.12.0.rc1"',
  # ...
]
```

**Comment by djhoese** [comment]
To everyone holding their breath about the hanging CI tests in my project: turns out it was an old upper limit on `bokeh` that we had that was causing an exception on import inside the `dask` scheduler/client and was just causing things to hang. Due to the multiprocess/threading nature and other warnings during the tests it took a while to find this error and realize the issue. Using a modern version of bokeh has fixed things for numpy 2.0 usage in my project's tests. The other `__getattr__` failure/warning was fixed earlier. Thanks everyone who helped fix these issues.

**Comment by henryiii** [comment]
An upper limit broke things? [Who would have thought...](https://iscinumpy.dev/post/bound-version-constraints/)

(I couldn't resist. :) )

**Comment by marcindulak** [comment]
> > Yes, it's not the first time they've done this kind of thing. It's causes more problems than it solves and is quite annoying. I think it's only Fedora that's doing this - or are you aware of others?
> 
> That does seem rather strange... Fedora usually rebuilds all existing packages in rawhide against the new python, the question is why the existing numpy in rawhide is an old version.
> 
> Their release monitoring does seem to think the "latest version" notification is for 2.0.0.dev0 so perhaps they just didn't realize that they are legitimately out of date?

The version of numpy https://src.fedoraproject.org/rpms/numpy in rawhide is https://github.com/numpy/numpy/releases/tag/v1.24.4, released by numpy on 2023-06-26 and first built on 2023-07-18 https://koji.fedoraproject.org/koji/buildinfo?buildID=2267273

The release monitoring of numpy https://release-monitoring.org/project/2509/ shows 2.0.0.dev0 retrieved on 2023-05-26, and the corresponding bug requesting the update was automatically opened the same day https://bugzilla.redhat.com/show_bug.cgi?id=2210209. Some releases seem not automatically marked in bugzilla https://pagure.io/releng/issue/11634.

We need remember that Fedora has only one version of a given package: when numpy is updated every package that uses it as a dependency is potentially affected. Therefore updating a version of a significant component like numpy needs to keep a balance between the freshness and the amount of work required to fix builds of the downstream dependent packages, see for example https://src.fedoraproject.org/rpms/numpy/pull-request/27.
A package update is ultimately a decision from the Fedora package maintainer. Additionally, when a larger update of a core component like Python is ongoing https://fedoraproject.org/wiki/Changes/Python3.12, some maintainers may prefer to avoid updating their packages (like numpy) to reduce the number of moving parts, others will use this as an opportunity to update their packages that break due to the Python update.

**Comment by eli-schwartz** [comment]
> We need to remember that Fedora has only one version of a given package: when numpy is updated every package that uses it as a dependency is potentially affected.

Yes but this isn't just a Fedora problem -- in fact it's such a widespread, pervasive problem across the entire computing industry that suggesting this needs to be remembered "for Fedora" seems... bizarre?

Python isn't npm, you can't load 50 distinct copies of a library some of which are the same version as each other and some of which aren't, into the same interpreter process and expect that to be business as usual. So this problem isn't even unique to Linux distros, *all* users of python are affected but sometimes only at the application level instead of the operating system level. It's nonetheless a serious topic even for them, the scope is merely smaller*, not non-existent.

> Additionally, when a larger update of a core component like Python is ongoing https://fedoraproject.org/wiki/Changes/Python3.12, some maintainers may prefer to avoid updating their packages (like numpy) to reduce the number of moving parts, others will use this as an opportunity to update their packages that break due to the Python update.

I should hope that maintainers who have found their packages break due to the python upgrade will upgrade their packages "like numpy" as well simply because they have to -- it's either upgrade numpy until it works, or ship a broken numpy that breaks all downstream dependent packages, or drop numpy from rawhide which breaks all downstream dependent packages in a much more... final... way.

Isn't this literally the entire point of upgrading python "in rawhide only" and doing so for *release candidates*? To find packages that break and fix them by upgrading to newer upstream releases or reporting bugs if there are no upstream releases to fix the problem?

This is even part of the Fedora docs on the python upgrade:
> There's also a benefit to the larger Python ecosystem: by building Fedora's packages against 3.12 while it's still in development, we can catch critical bugs before the final 3.12.0 release.

> Maintainers of packages that fail to rebuild during the rebuilds will be asked, using e-mail and bugzilla, to fix or remove their packages from the distribution.

This does require Fedora package maintainers to override their own personal desires when it comes to maintaining their packages, and bend to the will of the distro-wide policy on upgrading python and dealing with the fallout during (not after) the ongoing change in order to guarantee that said ongoing change succeeds...

...

It's very understandable that the release monitoring slipped up and the update wasn't noticed. But it's not really clear to me what this unrelated philosophical defense of retaining broken packages comes from? 😕

**Comment by eli-schwartz** [comment]
> The release monitoring of numpy https://release-monitoring.org/project/2509/ shows 2.0.0.dev0 retrieved on 2023-05-26, and the corresponding bug requesting the update was automatically opened the same day https://bugzilla.redhat.com/show_bug.cgi?id=2210209. Some releases seem not automatically marked in bugzilla https://pagure.io/releng/issue/11634.

Btw the larger issue here is that if the release monitoring is reporting unstable development tags as new versions then something is off as that simply should not happen ever. A dev tag isn't a new version, the tag name very specifically makes that clear with the "dev0" part. So the release monitoring should have ignored that, even if it also erroneously ignored older tags that *are* stable releases.

That's what I meant by:
> Their release monitoring does seem to think the "latest version" notification is for 2.0.0.dev0 so perhaps they just didn't realize that they are legitimately out of date?

i.e. since the release monitoring was flaky here and tries to suggest updating to incorrect releases, the release monitoring report was ignored and rightly so -- that's not a valid upgrade target! But that also probably meant there were no notifications for actual releases either, so it's pretty easy to overlook one package that has an unreported new version available.

**Comment by henryiii** [comment]
@neutrinoceros & @zoj613:

`python_version` is a two digit version. It does not include anything past `"3.12"`. It is defined as `'.'.join(platform.python_version_tuple()[:2])`. See [PEP 508](https://peps.python.org/pep-0508/).

If you really need the full thing there's `python_full_version`.

**Comment by zoj613** [comment]
> @neutrinoceros & @zoj613:
> 
> `python_version` is a two digit version. It does not include anything past `"3.12"`. It is defined as `'.'.join(platform.python_version_tuple()[:2])`. See [PEP 508](https://peps.python.org/pep-0508/).
> 
> If you really need the full thing there's `python_full_version`.

Thanks for the suggestion @henryiii , that seems to have solved the issue I was having. BUt now I get a new error:
```
  Traceback (most recent call last):
    File "/opt/python/cp312-cp312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/opt/python/cp312-cp312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/python/cp312-cp312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-rjh26k7q/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-rjh26k7q/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-rjh26k7q/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 7, in <module>
  ModuleNotFoundError: No module named 'numpy.distutils'
  error: subprocess-exited-with-error
```

It seems to be triggered by `from numpy.distutils.misc_util import get_info`. Is there an alternate `get_info` function in v1.26 now that distutils is no longer used?

**Comment by rgommers** [comment]
> It seems to be triggered by `from numpy.distutils.misc_util import get_info`. Is there an alternate `get_info` function in v1.26 now that distutils is no longer used?

I assume that that's inside your own package, trying to link against numpy-provided libraries? That's kind of a separate issue from Python 3.12 support, more a "what do I replace `numpy.distutils` functionality with". Maybe the logic SciPy uses helps: https://github.com/scipy/scipy/blob/2d27cf72806113e64f3eb4f3831dfd46bda1646c/scipy/meson.build#L30. If not, please feel free to open a new issue with more details, and Cc me.

**Comment by zoj613** [comment]
> > It seems to be triggered by `from numpy.distutils.misc_util import get_info`. Is there an alternate `get_info` function in v1.26 now that distutils is no longer used?
> 
> I assume that that's inside your own package, trying to link against numpy-provided libraries? That's kind of a separate issue from Python 3.12 support, more a "what do I replace `numpy.distutils` functionality with". Maybe the logic SciPy uses helps: [scipy/scipy@`2d27cf7`/scipy/meson.build#L30](https://github.com/scipy/scipy/blob/2d27cf72806113e64f3eb4f3831dfd46bda1646c/scipy/meson.build#L30). If not, please feel free to open a new issue with more details, and Cc me.

Yes, that was me trying to figure out how to replace `numpy.distutils` but it appears that https://github.com/numpy/numpy/pull/22538/files#diff-95416d9fa0c547f653edc04fe6055585e3dcb67d708440fc68f0afbddd11aaabR234-R256 has the answer.

**Comment by lithomas1** [comment]
Not to rush this, but is the 1.26 release scheduled for anytime soon?

I'm just asking since, even though I probably can build wheels from the beta for pandas, it doesn't makes sense for me to release 3.12 wheels before numpy, and I'd like to have wheels for pandas up before Python 3.12 comes out.

**Comment by rgommers** [comment]
The last needed feature (`f2py -c` support for Python 3.12) was just merged and backported to 1.26.x yesterday. I'd expect `1.26.0rc1` any minute now, and the final release 7-10 days after that. At least, that's what we discussed in the last community meeting. @charris may have a more authoritative answer.

> it doesn't makes sense for me to release 3.12 wheels before numpy

This is perfectly fine to do right now, as discussed higher up. Beyond the ~2 line patch to build against the beta or `rc1` with `cibuildwheel`, there are no downsides to doing your release now.

**Comment by skirpichev** [comment]
> The last needed feature (f2py -c support for Python 3.12) was just merged and backported to 1.26.x yesterday.

Great.  But the f2py doesn't work with the new default backend without additional requirements:
```
'meson-python;python_version>="3.12"',
'ninja;python_version>="3.12"'
```
@rgommers, maybe it does make sense to add these packages to the list of dependencies?  Or to the ``project.optional-dependencies`` section?

**Comment by rgommers** [comment]
> maybe it does make sense to add these packages to the list of dependencies? Or to the `project.optional-dependencies` section?

Good question @skirpichev. Definitely not a required dependency, but `optional-dependencies` may make sense. We don't list any of those right now - we also have functionality that depends on `cffi` for example. I'll open a separate issue for this now, to not mix it with the general Python 3.12 support one here.

**Comment by rgommers** [comment]
NumPy 1.26.0 is up on PyPI and conda-forge, so we should be all good here. Thanks all!

**Comment by draganmacosbht** [comment]
Is there any solution for the problem or only discussions
? :)
