### PR TITLE
BLD: update OpenBLAS to 0.3.21 and clean up openblas download test

### PR DESCRIPTION
**Pull request by mattip**
The builds have changed slightly:
- no longer need to check for manylinux1, manylinux2010 OpenBLAS builds: we exclusively build manylinux2014 wheels
- windows 64 bits compiles with gcc 10.3
- windows 32 bits compiles with gcc 8.3
- macos builds with gfortran from [MacPython/gfortran-install](https://github.com/MacPython/gfortran-install/blob/master/gfortran_utils.sh)
- consistently re-use the gfortran_utils.sh install script to provide the macos gfortran compiler
- check the OpenBLAS version on all wheels via `tools/openblas_support.py` and `threadpoolctl`

Maybe related to #22502

### CODE REVIEW

**Comment by mattip** [comment]
At this time the openblas-libs ppc64le 64-bit interface build times out, I hope to get the archive uploaded soon. But ppc64le is a best-effort platform, so I think it is OK to move forward without that build.

**Comment by charris** [comment]
close/reopen

**Comment by mattip** [comment]
Windows 64-bit [wheel builds](https://github.com/numpy/numpy/actions/runs/3387460614/jobs/5628235467#step:5:1263) and [regular builds](https://dev.azure.com/numpy/numpy/_build/results?buildId=26502&view=logs&j=c499766f-449b-5541-ed00-14b3885196ca&t=c16bbb4c-8d4f-5cec-143b-0575175479e7&l=1105) are failing with 
```
D:\a\1\s\openblas\openblas.a(memory.obj):memory.c:(.text+0xe6): \
    undefined reference to `__conio_common_vcprintf'
```

Windows 32-bit builds are passing.

**Comment by mattip** [comment]
@matthew-brett maybe this is due to using `choco install rtools` in the openblas build, or because we set `MSYSTEM=UCRT64` in the openblas build environment?

**Comment by mattip** [comment]
it may make sense to add threadpoolctl to test dependencies?

**Comment by charris** [comment]
I thought the conda fortran used libgfortran3.dylib. @isuruf what library does the fortran you made available use?

**Comment by isuruf** [comment]
@mattip, can you try delocate from https://github.com/matthew-brett/delocate/pull/167?
i.e. `pip install git+https://github.com/isuruf/delocate@search_usr_local#egg=delocate`

**Comment by mattip** [comment]
@isuruf using the version of delocate [delocates the files to numpy/.dylib](https://github.com/numpy/numpy/actions/runs/3434075733/jobs/5725052981#step:5:4475). However [f2py tests are failing](https://github.com/numpy/numpy/actions/runs/3434075733/jobs/5725052981#step:5:50989):
```
ImportError: dlopen(/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpom2lnnrm/_test_abstract_interface_TestAbstractInterface_ext_module.cpython-38-darwin.so, 2): \
    Library not loaded: @rpath/libgfortran.5.dylib
```

The gfortan link command is [here](https://github.com/numpy/numpy/actions/runs/3434075733/jobs/5725052981#step:5:50847)

Any thoughts?

**Comment by mattip** [comment]
Any macos people have an idea what changed with f2py tests? Somehow f2py runtimes are not finding `numpy/.dylibs/libgfortran.5.dylib` when they used to find `numpy/.dylibs/libgfortran.3.dylib`

**Comment by charris** [comment]
> Any macos people have an idea what changed with f2py tests?

I had to install gfortran in the test script for f2py, see #22534.

**Comment by mattip** [comment]
@charris thanks, I added the gfortran install commands to the macos wheel build

**Comment by charris** [comment]
I suspect the problem is not using the mac installer, which puts things where they belong. Can you get a dmg package?

**Comment by mattip** [comment]
I wonder how scipy handles this. The strange thing is that on azure the same macos tests are passing.

**Comment by charris** [comment]
Whoa, looks like the mac problem is solved.

File: numpy/f2py/tests/test_compile_function.py [hunk 1]
```diff
@@ -68,7 +68,20 @@ def test_f2py_init_compile(extra_args):
...
         # result of the sum operation
-        return_check = import_module(modname)
+        if sys.platform == 'darwin':
+            print("xxxxxxxxxxxxxxxxxxxxxxxxxxx")
+            import subprocess
+            print(moddir, modname)
+            try:
+                subprocess.run(["ls", moddir])
+                print("yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy")
+                subprocess.run(["otool", "-L", moddir + '/' + modname + '*.dyld'])
```
[the remark this answers is not in the document]
Comment (mattip) [reply numpy/f2py/tests/test_compile_function.py:78]: thanks, fixed

**Comment by mattip** [comment]
Whew. Finally I got the `otool -L` output for the f2py-built shared object. No big surprise, since the error message mentioned `@rpath/libgfortran.5.dylib`
```
<tmp>/tmpjnw10nwm/_test_ext_module_5404.cpython-38-darwin.so:
 	@rpath/libgfortran.5.dylib (compatibility version 6.0.0, current version 6.0.0)
 	@rpath/libgcc_s.1.1.dylib (compatibility version 1.0.0, current version 1.1.0)
 	@rpath/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
```

Now how do I show the active dylib search path?

File: .github/workflows/circleci.yml [hunk 2]
```diff
@@ -2,6 +2,8 @@
 #
 # if: github.repository == 'numpy/numpy'
 
+name: CircleCI artifact redirector
+
```
Comment (mattip) [inline .github/workflows/circleci.yml:6]: A small cleanup to improve the UX when looking at the github action summaries

File: numpy/distutils/command/build_ext.py [hunk 3]
```diff
@@ -586,6 +586,13 @@ def build_extension(self, ext):
             # not using fcompiler linker
             self._libs_with_msvc_and_fortran(
                 fcompiler, libraries, library_dirs)
+            if ext.runtime_library_dirs:
+                # gcc adds RPATH to the link. On windows, copy the dll into
+                # self.extra_dll_dir instead.
+                for d in ext.runtime_library_dirs:
+                    for f in glob(d + '/*.dll'):
+                        copy_file(f, self.extra_dll_dir)
+                ext.runtime_library_dirs = []
```
Comment (mattip) [inline numpy/distutils/command/build_ext.py:595]: This change is connected to the use of a DLL directly from the OpenBLAS build, rather than pulling out the `libopenblas.a` and wrapping it via gfortran to create another DLL. Apparently numpy/distutils was never set up to do this before.

File: tools/wheels/cibw_test_command.sh [hunk 4]
```diff
@@ -5,19 +5,27 @@ set -xe
...
     # GH 20391
     PY_DIR=$(python -c "import sys; print(sys.prefix)")
     mkdir $PY_DIR/libs
 fi
-
+if [[ $RUNNER_OS == "macOS"  && $RUNNER_ARCH == "X64" ]]; then
+    # Not clear why this is needed but it seems on x86_64 this is not the default
+    # and without it f2py tests fail
+    export DYLD_LIBRARY_PATH=/usr/local/lib
+fi
```
Comment (mattip) [inline tools/wheels/cibw_test_command.sh:19]: This took way to long to work out.

**Comment by mattip** [comment]
Travis CI build is failing for ppc64le when using 64-bit interfaces. I will disable that job until someone can figure out why the openblaslib build of that times out.

**Comment by mattip** [comment]
Assuming CI passes I think this is ready for review. If desired, I could clean up the git history into meaningful commits, or the whole thing could be squash-merged.

**Comment by mattip** [comment]
Windows + pypy is segfaulting
```
numpy\lib\tests\test_format.py . [ 56%]
.................................s
D:\a\numpy\numpy/tools/wheels/cibw_test_command.sh: line 29:  2011 Segmentation fault
```

I suspect the `test_large_archive` test and will skip it. I don't know what the connection to the OpenBLAS version is, but I don't think it is worth diving into.

**Comment by mattip** [comment]
CI is passing

**Comment by mattip** [comment]
This will close #22502

File: .travis.yml [hunk 5]
```diff
@@ -32,7 +32,7 @@ jobs:
       env:
        # use OpenBLAS build, not system ATLAS
        - DOWNLOAD_OPENBLAS=1
-       - NPY_USE_BLAS_ILP64=1
+       # - NPY_USE_BLAS_ILP64=1   # the openblas build fails
```
Comment (charris) [inline .travis.yml:35]: Maybe open an issue for this?

**Comment by charris** [comment]
Thanks Matti. I suspect this isn't the last time we will deal with these problems :)
