### PR TITLE
BUG: missing comma disabled some header checks

### LINKED ISSUE #8693: macOSX / clang compile fails with undefined locale identifiers
macOSX build now failing with undefined locale identifiiers, after merge of #7997 :

```
clang: numpy/core/src/multiarray/numpyos.c
numpy/core/src/multiarray/numpyos.c:518:5: error: use of undeclared identifier 'locale_t'
    locale_t clocale;
```

https://travis-ci.org/MacPython/numpy-wheels/jobs/205229905#L3775

Errors result from merge of https://github.com/numpy/numpy/pull/7997 - commit 23ac8554b builds (pre-merge), commit 7bc881d05 breaks (the merge commit).

@juliantaylor - any thoughts?

### PR DESCRIPTION
**Pull request by juliantaylor**
closes gh-8693

### CODE REVIEW

**Comment by matthew-brett** [comment]
Looks right to me.  Fixes compilation on macOS.

**Comment by juliantaylor** [comment]
odd that HAVE_DLFCN_H is somehow defined on my machine despite the broken check, must be defined by the python header itself somehow.
added an explicit npy_config.h include due to "include what you use directly"
