### PR TITLE
MAINT: Move export for scipy arm64 helper into main module

### PR DESCRIPTION
**Pull request by charris**
Backport of #22939.

This is a follow up to gh-22679 which addressed gh-22673.

The main thing is that we want the functions to be available after importing NumPy, so they need to be part of multiarray. However, `npymath` is a static library, so the symbols are not really exported there.  The former PR did actually work in practice but this seems like it is technically the right place?

For some reason, I had to add nextafter to be able to do:

    from scipy.spatial.distance import euclidean

with the SciPy 1.9.3 wheels.  SciPy test collection works with this for the 1.9.3 wheel, so this should be all the symbols hopefully.

### CODE REVIEW

**Comment by charris** [comment]
The failure seem due to
```
2023-01-08T22:50:53.2026876Z numpy/core/src/umath/loops.c.src:1497:31: error: implicit declaration of function ‘npy_nextafter’; did you mean ‘npy_nextafterl’? [-Werror=implicit-function-declaration]
```

**Comment by charris** [comment]
I suspect there is a missing backport.

File: numpy/core/include/numpy/npy_math.h [hunk 1]
```diff
@@ -184,29 +184,23 @@ NPY_INPLACE double npy_atan2(double x, double y);
...
-/* due to a build problem with scipy, export these as functions */
-NPY_INPLACE double npy_asinh(double x);
-NPY_INPLACE double npy_copysign(double y, double x);
-NPY_INPLACE double npy_log1p(double x);
-#else
-#define npy_asinh asinh
-#define npy_copysign copysign
-#define npy_log1p log1p
-#endif
 double npy_nextafter(double x, double y);
```
Comment (mattip) [inline numpy/core/include/numpy/npy_math.h:202]: I restored this line which should not be removed

Comment (seberg) [reply numpy/core/include/numpy/npy_math.h:202]: Ah, thanks.  So that is why I had to add nextafter, but it was previously no issue.  I guess it could be excluded from the other file in that case, but seems it doesn't matter?

Comment (mattip) [reply numpy/core/include/numpy/npy_math.h:202]: It needs to be in both files for this branch. One is compiled into `libnpy_math.a`, this is the one that is removed from `main` but on this branch it is alive and well. The other implementation is exported from the main numpy namespace because of `<mumble>macos arm64 build linking problem</mumble>`

**Comment by charris** [comment]
Thanks Matti.

File: numpy/core/include/numpy/npy_math.h (hunk 1 above)
Comment (charris) [reply numpy/core/include/numpy/npy_math.h:202]: @seberg @mattip 

This seems to be causing problems with the macosx m1 wheels, the linker complains of two symbols `_npy_nextafter`, which I suspect is because of long double being double on the m1 platform. This doesn't seem to be a problem in main.

Comment (seberg) [reply numpy/core/include/numpy/npy_math.h:202]: Arrgg, I guess that because `npy_nextafter` is already here, it should not have been included in `arm64_exports.c` for the backport...
