### ISSUE TITLE
apply_along_axis stopped working with non-arrays in 1.12.0rc1

### ISSUE THREAD

**Issue by akhmerov** [numpy/numpy#8419]
In v1.12.0rc1

```python
import numpy as np
np.apply_along_axis((lambda x: (x[1], x[0])), 1, np.random.randn(2, 4))
```
raises `AttributeError: 'tuple' object has no attribute 'shape'`

Is this intended?

**Comment by charris** [comment]
@bennyrowland  Yours?

**Comment by bennyrowland** [comment]
@charris Mine. I have submitted a new PR to fix this: #8426 which also has a new test based on @akhmerov's minimal example above. Sorry for the slow response, I have been off network for the holidays.

**Comment by charris** [comment]
Closed by #8426.
