### ISSUE TITLE
assert_array_equal raises AttributeError instead of AssertionError (regression)

### ISSUE THREAD

**Issue by kdebrab** [numpy/numpy#12942]
When applying assert_array_equal on an (unequal) arrays with datetimes, an AttributeError is (incorrectly) raised in numpy 1.16.1.

In numpy 1.16.0, the behaviour was still correct, namely raising an AssertionError.

### Reproducing code example:

```python
import numpy as np
import datetime as dt
a = np.array([dt.datetime(2000,1,1), dt.datetime(2000, 1, 2)])
np.testing.assert_array_equal(a, a[::-1])
```

### Error message:

```
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\IPython\core\interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-27-fd47e00f876e>", line 1, in <module>
    np.testing.assert_array_equal(a, a[::-1])
  File "C:\Python36\lib\site-packages\numpy\testing\_private\utils.py", line 896, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "C:\Python36\lib\site-packages\numpy\testing\_private\utils.py", line 805, in assert_array_compare
    + array2string(max_abs_error))
  File "C:\Python36\lib\site-packages\numpy\core\arrayprint.py", line 687, in array2string
    if a.size == 0:
AttributeError: 'datetime.timedelta' object has no attribute 'size'

```
### Numpy/Python version information:

1.16.1 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]

**Comment by raldridge11** [comment]
I have also run across this issue with numpy 1.16.1.

**Comment by charris** [comment]
Probably from the datetime changes.

**Comment by charris** [comment]
This should be an easy fix. @mattip.

**Comment by mattip** [comment]
introduced in #12591 by using `array2string(a)` instead of `str(a)`. For object arrays `x`, `y`, `a = abs(x - y).max()` can be a python object not an ndarray
