### ISSUE TITLE
Cannot pickle random state

### ISSUE THREAD

**Issue by giuse** [numpy/numpy#14210]
Still unsure if this problem is on numpy's side, but I tried downgrading to 1.14 (minimum numpy version for my dependencies) and verified it all works, no errors.
Given the recent changes on `random` I thought of bringing it up with you guys, particularly @charris @mattip (from https://github.com/numpy/numpy/pull/14207 )

I am sorry I could not isolate a simple reproducible example yet, my setup is inconveniently convoluted ATM. 

I am using [Ray](https://github.com/ray-project/ray) to parallelize calls to the [OpenAI Gym](https://github.com/openai/gym), this in turn implying a numpy random state is pickled for storage on its Redis-based object store. The un-pickling after Redis does not find the function [`__randomstate_ctor()`](https://github.com/numpy/numpy/blob/master/numpy/random/_pickle.py#L62).
I tried adding it to the [__init()__](https://github.com/numpy/numpy/blob/master/numpy/random/__init__.py) on the same fashion as (the suspiciously similar) [__RandomState_ctor()](https://github.com/numpy/numpy/blob/master/numpy/random/__init__.py#L194), but to no avail.

My hope is that someone with a better knowledge of this code will find something useful in the error.

### Reproducing code example:

Sorry too complex yet, unable to isolate it.

### Error message:

(Getting one of each from each worker, hundreds of them running async)

```
2019-08-06 14:18:59,907	ERROR worker.py:1714 -- Failed to unpickle the remote function '__main__.<lambda>' with function ID 84d9aba7e5b48a67d1b84d50bbf3f47e94bd0f4b. Traceback:
Traceback (most recent call last):
  File "/home/giuse/.local/share/virtualenvs/des-htl_CtVS/lib/python3.6/site-packages/ray/function_manager.py", line 424, in fetch_and_register_remote_function
    function = pickle.loads(serialized_function)
AttributeError: Can't get attribute '__randomstate_ctor' on <module 'numpy.random._pickle' from '/home/giuse/.local/share/virtualenvs/des-htl_CtVS/lib/python3.6/site-packages/numpy/random/_pickle.py'>

2019-08-06 14:18:59,861	ERROR worker.py:1654 -- Possible unhandled error from worker: ray_BlockWorker:run() (pid=28613, host=diufrm148)
  File "/home/giuse/des/block_worker.py", line 61, in run
    fitnesses = self.parallel_eval(population)
  File "/home/giuse/des/block_worker.py", line 91, in parallel_eval
    return ray.get([ ev.evaluate.remote(ind) for ev, ind in zip(self.fitness_evaluators, population) ])
ray.exceptions.RayTaskError: ray_FitnessEvaluator:evaluate() (pid=29830, host=diufrm148)
  File "pyarrow/serialization.pxi", line 461, in pyarrow.lib.deserialize
  File "pyarrow/serialization.pxi", line 424, in pyarrow.lib.deserialize_from
  File "pyarrow/serialization.pxi", line 275, in pyarrow.lib.SerializedPyObject.deserialize
  File "pyarrow/serialization.pxi", line 174, in pyarrow.lib.SerializationContext._deserialize_callback
AttributeError: Can't get attribute '__randomstate_ctor' on <module 'numpy.random._pickle' from '/home/giuse/.local/share/virtualenvs/des-htl_CtVS/lib/python3.6/site-packages/numpy/random/_pickle.py'>
```

### Numpy/Python version information:

```
1.17.0 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
```

**Comment by charris** [comment]
@bashtage @mattip Thoughts?

**Comment by bashtage** [comment]
First guess is that the installation has mismatches between workers and controllers. In particular, the version used to unpickle doesn't match the version used to pickle.

**Comment by giuse** [comment]
Yeah good thought, I am a strict pipenv user so I did not even consider that. Anyway I checked and I have no numpy installed system-wide. Made sure both with `apt`, `pip`, `pip3`, and by running both `python` and `python3` consoles and getting `ModuleNotFoundError` when trying to import.

I am positive the only numpy on the system is through pipenv, and that that is a `1.17.0`. Bummers.

**Comment by bashtage** [comment]
Can you pop a `dir(np.random._pickle)` in your code?  Does it show this function?
If it looks normal, what does `print(np.random._pickle.__randomstate_ctor())` return?

**Comment by giuse** [comment]
Here, I stuck this:

```python
print(dir(np.random._pickle))
print(np.random._pickle.__randomstate_ctor())
exit()
```

on top of the init of the "leaf" ("child-most"?) objects.

(Yay for printf-debugging in distributed computing -- the alternative being one debugger embedding in each subprocess... If anyone has any idea of how to restrict Ray to a sequential execution for debugging purposes I would be plenty grateful.)

Here's the output:

```
(pid=29680) ['BitGenerators', 'Generator', 'MT19937', 'PCG64', 'Philox', 'RandomState', 'SFC64', '__bit_generator_ctor', '__builtins__', '__cached__', '__doc__', '__file__', '__generator_ctor', '__loader__', '__name__', '__package__', '__randomstate_ctor', '__spec__']

2019-08-07 10:35:15,105	ERROR worker.py:1654 -- Possible unhandled error from worker: ray_FitnessEvaluator:__init__() (pid=29623, host=free)
  File "/home/giuse/des_debug/fitness_evaluator.py", line 36, in __init__
    print(np.random._pickle.__randomstate_ctor())
AttributeError: module 'numpy.random._pickle' has no attribute '_FitnessEvaluator__randomstate_ctor'

2019-08-07 10:35:15,105	ERROR worker.py:1654 -- Possible unhandled error from worker: ray_FitnessEvaluator:update_ind() (pid=29623, host=free)
  File "/home/giuse/des_debug/fitness_evaluator.py", line 36, in __init__
    print(np.random._pickle.__randomstate_ctor())
AttributeError: module 'numpy.random._pickle' has no attribute '_FitnessEvaluator__randomstate_ctor'

2019-08-07 10:35:15,105	ERROR worker.py:1654 -- Possible unhandled error from worker: ray_FitnessEvaluator:evaluate() (pid=29623, host=free)
  File "/home/giuse/des_debug/fitness_evaluator.py", line 36, in __init__
    print(np.random._pickle.__randomstate_ctor())
AttributeError: module 'numpy.random._pickle' has no attribute '_FitnessEvaluator__randomstate_ctor'
```

Again, keep in mind that `_FitnessEvaluator__randomstate_ctor` is the decoration added by Ray on top of `__randomstate_ctor`, and that with downgrading to numpy 1.14 this works perfectly fine.
I would read this printout as: 1. the function `__randomstate_ctor` is correctly available directly from numpy, but 2. when someone embeds the random state (the gym) and gets then pickled (by ray) that function is either pickled or unpickled incorrectly. I would look for the culprit on the code responsible to pickling/unpickling that function (and the random state as a whole). Thanks!

**Comment by bashtage** [comment]
Looks like class name mangling. 

https://docs.python.org/3.5/reference/expressions.html?highlight=mangling#index-5

What I suspect is happening is that _FitnessEvaluator is poking that attribute __randomstate_ctor into itself, and then when it tried to access it, it has been mangled and so cannot find it. 

Does Ray profess to be compatible with NumPy 1.17?  Is this something that they need to fix/test against?

**Comment by giuse** [comment]
Yup definitely name mangling, thanks for the pointer!

- Class FitnessEvaluator does not even import numpy. I had to add the import in the test below for it to work, and finding it name-mangled into my class after deserialization is baffling. It seems to me that if the problem was there it would not work with 1.14 either, right?
- OpenAI does not profess much in terms of compatibility :) their `setup.py` requires numpy [1.10.04 or above](https://github.com/openai/gym/blob/master/setup.py#L34), I guess they did not expect a minor-version change to break functionality ;)

I run the same printf code in the same place but with numpy 1.14, here's the result(ing errro):

2019-08-07 11:25:40,517	ERROR worker.py:1654 -- Possible unhandled error from worker: ray_FitnessEvaluator:update_ind() (pid=32718, host=free)
  File "/home/giuse/des/fitness_evaluator.py", line 33, in __init__
    print(dir(np.random._pickle))
AttributeError: module 'numpy.random' has no attribute '_pickle'

My money is still on pickling problems after the random state overhauling, possibly sneaked into production due to undertesting if @charris is in the right place
https://github.com/numpy/numpy/pull/14207#issuecomment-518698575

**Comment by bashtage** [comment]
You should probably report it to https://github.com/openai/gym too since AFAIK the NumPy code is valid python and gym appears to be making some assumptions about `__func` functions that are not valid. 

The same issue will arise when someone tries to use the new random number generator `Generator` which shares the same pickling strategy. 

> * It seems to me that if the problem was there it would not work with 1.14 either, right?

This sounds right, although it is possible that `__Function` and `__function` are treated differently in mangling. Note that the helper functions have different capitalization.  I have no idea if this is intentional. 

> * I guess they did not expect a minor-version change to break functionality

NumPy and a lot of the scientific stack does not follow [SemVer](https://semver.org/) so 1.16.x to 1.17.0 is more like 16.x to 17.0 in a SemVer scheme.

**Comment by giuse** [comment]
Thanks for the pointer, issue referenced! https://github.com/openai/gym/issues/1641

I am aware of (and again, pretty baffled by) the problems with [capitalization](https://github.com/numpy/numpy/blob/master/numpy/random/__init__.py#L194) in the module. I actually tried playing around with the naming (e.g. lowercasing that line, either substitute or duplicate) to no avail.

Yeah function names with arbitrary capitalization and major projects not following semantic versioning are two more things I am not used to :) I guess it goes to show how new I am to Python :D sorry for the blunders!

Would you propose anyone we could ping who could contribute an alternative idea or perspective? @mattip ? @charris ? Anyone?

**Comment by bashtage** [comment]
@rkern know a lot more than I about these kinds of corner cases.

**Comment by rkern** [comment]
> Again, keep in mind that `_FitnessEvaluator__randomstate_ctor` is the decoration added by Ray on top of `__randomstate_ctor`, and that with downgrading to numpy 1.14 this works perfectly fine.

What do you mean "decoration added by Ray"? You mean only in the printout of the `AttributeError` message? Because if it's adjusting the name that is actually requested from `np.random._pickle`, then _that's_ your problem.

Where is `FitnessEvaluator` defined? I don't see it in `gym` or `ray`. Is that in your code? I'm concerned that something along that chain might be replacing modules like `np.random._pickle` with fake-module objects, and that's creating name mangling where there should be no name mangling. Instead of `gym`, you probably need to look at `ray`.

I do not believe this is a numpy bug.

**Comment by rkern** [comment]
Ah, never mind about the mangling. It isn't Ray that's doing it. Python does it inside of any method of a class. Can you put these `print()`s into a function and call that function in your `FitnessEvaluator` method? That should bypass the name mangling.

```python
def printer():
    from numpy.random import _pickle
    
    print(_pickle.__randomstate_ctor('MT19937'))


class FitnessEvaluator(object):
    def __init__(self):
        printer()


FitnessEvaluator()
```

**Comment by rkern** [comment]
Note that you have to explicitly import `np.random._pickle` first. You can't just `import numpy as np` and then access `np.random._pickle`. It's not one of the modules that is always imported.

**Comment by bashtage** [comment]
Do you think not importing _pickle as part of import numpy is the
difference between 1.16 and 1.17?

**Comment by rkern** [comment]
It should only matter for the test code that @giuse is writing to diagnose the issue; that's the cause of the `AttributeError: module 'numpy.random' has no attribute '_pickle'` exceptions that are obscuring the actual issue. In the actual code that's failing, it finds `_pickle` just fine and it's `__randomstate_ctor` that isn't being found.

**Comment by rkern** [comment]
Some basic usages seem to work okay (though I haven't played around much with Ray, yet):

```python
import numpy as np
import ray


def main():
    ray.init()
    prng = np.random.RandomState(123456)
    prng_obj = ray.put(prng)
    prng2 = ray.get(prng_obj)
    print(prng)
    print(prng_obj)
    print(prng2)

    func = lambda: prng
    remote_func = ray.remote(func)
    print(ray.get(remote_func.remote()))


if __name__ == '__main__':
    main()
```

I don't think we can make much more progress without code that demonstrates the problem. @giuse, even if you can't make a minimal running example, is it possible for you to post the code? That may help me make a minimal example if I can see in a little more detail how you are using `ray` and where the `RandomState` instance is flowing.

**Comment by bashtage** [comment]
> It should only matter for the test code that @giuse is writing to diagnose the issue; that's the cause of the `AttributeError: module 'numpy.random' has no attribute '_pickle'` exceptions that are obscuring the actual issue. In the actual code that's failing, it finds `_pickle` just fine and it's `__randomstate_ctor` that isn't being found.

I was wondering (out loud) if something like #14141 could be going on where some upstream package is making assumptions about modules, and ignoring or otherwise treating modules that are imported in Cython differently. Just trying to guess why the old version pickled and this one does not.

**Comment by giuse** [comment]
Wow thanks for your answers! I will try to answer all, thanks for your contributions!!

> Where is `FitnessEvaluator` defined? I don't see it in `gym` or `ray`.

As mentioned it is my own code, though it does not even import numpy.

> Can you put these print()s into a function and call that function in your FitnessEvaluator method? That should bypass the name mangling.

Awesome, thanks! Here's the code I run:
```python
def printer():
	from numpy.random import _pickle
	print(f"Dir: {dir(np.random._pickle)}")
	print(f"Call: {_pickle.__randomstate_ctor('MT19937')}")

@ray.remote
class FitnessEvaluator:
	def __init__():
		printer()
		# [rest of program, no call to exit()]
```
The output on 1.14 (I guess as expected but hey completeness):
```
2019-08-08 14:00:32,952	ERROR worker.py:1654 -- Possible unhandled error from worker: ray_BlockWorker:run() (pid=30730, host=free)
  File "/home/giuse/des_debug_1.14/block_worker.py", line 73, in run
    fitnesses = self.parallel_eval(population)
  File "/home/giuse/des_debug_1.14/block_worker.py", line 118, in parallel_eval
    return ray.get(result_ids)
ray.exceptions.RayTaskError: ray_FitnessEvaluator:evaluate() (pid=30994, host=free)
  File "/home/giuse/des_debug_1.14/fitness_evaluator.py", line 41, in __init__
    printer()
  File "/home/giuse/des_debug_1.14/fitness_evaluator.py", line 28, in printer
    from numpy.random import _pickle
ImportError: cannot import name '_pickle'
```
The output on 1.17 (FYI these are a selection of the different types of output out of hundreds or repetitions):
```
(pid=1294) Dir: ['BitGenerators', 'Generator', 'MT19937', 'PCG64', 'Philox', 'RandomState', 'SFC64', '__bit_generator_ctor', '__builtins__', '__cached__', '__doc__', '__file__', '__generator_ctor', '__loader__', '__name__', '__package__', '__randomstate_ctor', '__spec__']
(pid=1294) Call: RandomState(MT19937)

2019-08-08 14:08:52,458	ERROR worker.py:1714 -- Failed to unpickle the remote function '__main__.<lambda>' with function ID 84d9aba7e5b48a67d1b84d50bbf3f47e94bd0f4b. Traceback:
Traceback (most recent call last):
  File "/home/giuse/.local/share/virtualenvs/des_debug_1.17-_YO0kpRV/lib/python3.6/site-packages/ray/function_manager.py", line 424, in fetch_and_register_remote_function
    function = pickle.loads(serialized_function)
AttributeError: Can't get attribute '__randomstate_ctor' on <module 'numpy.random._pickle' from '/home/giuse/.local/share/virtualenvs/des_debug_1.17-_YO0kpRV/lib/python3.6/site-packages/numpy/random/_pickle.py'>

2019-08-08 14:08:56,030	ERROR worker.py:1654 -- Possible unhandled error from worker: ray_FitnessEvaluator:__init__() (pid=1386, host=free)
  File "pyarrow/serialization.pxi", line 461, in pyarrow.lib.deserialize
  File "pyarrow/serialization.pxi", line 424, in pyarrow.lib.deserialize_from
  File "pyarrow/serialization.pxi", line 275, in pyarrow.lib.SerializedPyObject.deserialize
  File "pyarrow/serialization.pxi", line 174, in pyarrow.lib.SerializationContext._deserialize_callback
AttributeError: Can't get attribute '__randomstate_ctor' on <module 'numpy.random._pickle' from '/home/giuse/.local/share/virtualenvs/des_debug_1.17-_YO0kpRV/lib/python3.6/site-packages/numpy/random/_pickle.py'>

2019-08-08 14:08:57,041	ERROR worker.py:1654 -- Possible unhandled error from worker: ray_BlockWorker:run() (pid=1242, host=free)
  File "/home/giuse/des_debug_1.17/block_worker.py", line 73, in run
    fitnesses = self.parallel_eval(population)
  File "/home/giuse/des_debug_1.17/block_worker.py", line 118, in parallel_eval
    return ray.get(result_ids)
```

FYI BlockWorker is a ray Actor which calls FitnessEvaluator (another Actor). The latter includes a gym environment. Also FYI if curious the work is mentioned [[here]](https://twitter.com/giuse_tweets/status/1145457742242570240).

> Note that you have to explicitly import np.random._pickle first. You can't just import numpy as np and then access np.random._pickle. It's not one of the modules that is always imported.

Thanks! I am picking these things up as I go, none of these concepts are new to me but the way Python handles them is, so I appreciate the thoroughness :)

> It should only matter for the test code that @giuse is writing to diagnose the issue; that's the cause of the AttributeError: module 'numpy.random' has no attribute '_pickle' exceptions that are obscuring the actual issue. In the actual code that's failing, it finds _pickle just fine and it's __randomstate_ctor that isn't being found.

I agree, sorry for that, I do know how the `__init__.py` works in principle but yesterday I did not pay attention.

> Some basic usages seem to work okay (though I haven't played around much with Ray, yet)

Yup, tried many variants of that example (also including gym) but couldn't reproduce easily, else I would have included it in the issue.

> Even if you can't make a minimal running example, is it possible for you to post the code?

Apologies, I would have done it already if I could. The code is scheduled for public release in a month if everything goes well, then I will be able to offer a nontrivial example to reproduce the error. I was hoping this could be caught beforehand so that I will not have to lock numpy to an older version in the first release -- not important, but I sincerely respect your work, enough that I am willing to invest this effort in what is admittedly a blind chase just so I can declare I am using your last version :)

> I was wondering (out loud) if something like #14141 could be going on where some upstream package is making assumptions about modules, and ignoring or otherwise treating modules that are imported in Cython differently. Just trying to guess why the old version pickled and this one does not.

Yup this is the reason why I opened the issue, I was hoping for someone to have a look at this and having a deja vu :)

**Comment by bashtage** [comment]
> Apologies, I would have done it already if I could. The code is scheduled for public release in a month if everything goes well, then I will be able to offer a nontrivial example to reproduce the error.

It would be helpful if you can make a trivial example -- as simple as possible -- that produces the error.  It can be completely contrived as long as it raises. 


> Yup this is the reason why I opened the issue, I was hoping for someone to have a look at this and having a deja vu :)

If you are willing to modify your numpy install, you can try adding `from . import _pickle` the `__init__.py` file in numpy/random. I doubt this will fix it, but it is pretty easy to determine if that is an issue.

**Comment by bashtage** [comment]
One more question, does the same error occur when you run locally or on a cluster? Your OP mentions Redis which suggests that you are working on a cluster.

**Comment by giuse** [comment]
> If you are willing to modify your numpy install, you can try adding from . import _pickle the __init__.py file in numpy/random. I doubt this will fix it, but it is pretty easy to determine if that is an issue.

It does solve the issue! No more errors! Nice catch man :)

Isn't this weird though?? I had to try the code several time to convince myself this really fixes it. Is it possible that somewhere in the pickling process this https://github.com/numpy/numpy/issues/14210#issuecomment-519196685 was not taken into consideration?

(For the interested reader: as I mentioned I use pipenv, and I already made a copy of my code for this issue so I can continue working on it in isolation. The debug copy runs an independent installation, so  editing a project's numpy is just `EDITOR=<your_choice> pipenv open numpy` from its folder)

> One more question, does the same error occur when you run locally or on a cluster? Your OP mentions Redis which suggests that you are working on a cluster.

Single machine; unfortunately I have not been able to find a way to tell Ray to run single-threaded and sequential yet (debug would be soooo much easier), but at least I am making sure it's all local for these tests. If pickling to (local) Redis goes well I expect it shouldn't generate new problems after switching to multiple machines, but let's cross that bridge when we get there :)

**Comment by bashtage** [comment]
> It does solve the issue! No more errors! Nice catch man :)

This tells us that something (Ray?) is doing some magic when determining which modules need to be available, and that it doesn't under Cython.

The simplest solution (for the ecosystem, but not NumPy) is probably to manually import this module (and add a note as to why).

**Comment by giuse** [comment]
Correct me if I'm wrong, but I understood that in Python a library wishing to claim to be serializable should offer a one-shot interface to pickle and unpickle, such that other libraries wishing to serialize it need making no assumptions. And that actually ray/gym made no assumption, where it should have assumed that an extra import was necessary in order to serialize numpy.

Are you proposing that the correct fix (say future pull request) is to open not the numpy installation, but rather the ray/gym installation, and placing a call to `import numpy.random._pickle` before they do a standard call to pickle on numpy objects? Is this extra import a standard that everyone using numpy should be aware of? And why was it unnecessary before?

Sorry I've not even gotten into Cython references and I'm confused already...

**Comment by bashtage** [comment]
Something in your stack is determining which modules should be available in workers. I *guess* that it is doing this by inspecting sys.modules.  Since _pickle is only imported when a RandomState object is deserialized, then it won't appear here.  The fact that adding _pickle to `__init__` seems to have resolved the issue also points at some method of introspection being used to determine modules by the runner. 

However the available modules are being determined, the mechanism differs from the usual method of resolving a module in standard python -- if it did, the `from _pickle import  __randomstate_ctor` would not fail. 


> Are you proposing that the correct fix (say future pull request) is to open not the numpy installation, but rather the ray/gym installation, and placing a call to `import numpy.random._pickle` before they do a standard call to pickle on numpy objects? Is this extra import a standard that everyone using numpy should be aware of? And why was it unnecessary before?

Ideally gym/Ray would follow standard Python semantics and use the path when resolving modules. This requires sharing the path to all workers, which they might be trying to avoid. 

Some distributed systems use the path.  For example, Apache Spark allows the python path to be set when launching a session, as long as this location needs to be resolvable by the cluster nodes.  If you cannot set this path, you can ship a zip file containing python modules to workers which are then placed on a local path.

**Comment by giuse** [comment]
Thanks @bashtage, that is a very educative answer!
Ok I guess the next step then is to try and ping ray/gym linking them this comment and see what they think of it.

Does this mean that the behavior of numpy is correct and as expected and we can actually close this issue?

**Comment by bashtage** [comment]
NumPy is not wrong.  However, this issue has now caught two applications that use NumPy and so a decision needs to be taken about whether NumPy should eat the technical debt and possibly performance hit to simplify these applications.   You should leave it open until a decision is taken on whether modules that are only included in Cython code are going to be included in `__init__`, as in #14163.

**Comment by seberg** [comment]
So would an `if False: import numpy.random._pickle` in the numpy code solve the issue here as well?!

**Comment by bashtage** [comment]
@guise Can you try @seberg 's suggesting by modifying you `random/__init__.py` with only the `if False:...` line?  

My bet is no.

**Comment by giuse** [comment]
Uhm the way I see it 1. code after an `if False:` should never be loaded, so I am confused as to why should it be consequential, 2. unsure about where "in the numpy code" should I add that line, guessing in `numpy/random/__init__.py`, but then 3. if so I guess you meant `from . import _pickle`

Anyway I tried both
```python
if False: import numpy.random._pickle
```
and 
```python
if False: from . import _pickle
```
in `numpy/random/__init__.py` replacing the working `from . import _pickle` and indeed no, neither works.

If there is some side effect in Python such that mentioning an `import` in an `if False:` clause does/changes anything at all I would very much like to learn about it before I encounter it in the wild :) thanks!

**Comment by seberg** [comment]
Yeah, I guess that was silly. The thing is that there are some (or maybe just PyInstaller), that actually manually parses for import statements to know which files to package. I guess this is completely different, although somehow slightly related.

**Comment by giuse** [comment]
No worries, thanks for pitching in!

**Comment by rkern** [comment]
What's weird is that it looks like the worker does get a `numpy.random._pickle` module; it just can't find the functions in it.

```
AttributeError: Can't get attribute '__randomstate_ctor' on <module 'numpy.random._pickle' from '/home/giuse/.local/share/virtualenvs/des-htl_CtVS/lib/python3.6/site-packages/numpy/random/_pickle.py'>
```

That wouldn't indicate a `PyInstaller`-like static analysis of what modules to push to the worker. The module's there; the function isn't, at least, not when the deserialization code is trying to access it. It smells more like some kind of circular import issue where something in the execution of the `numpy/random/_pickle.py` code is causing something to look up `__randomstate_ctor()` in `numpy.random._pickle` before it has gotten around to executing it, but I don't see how the `pyarrow` deserialization stuff that we see in the traceback could possibly be in the middle of that. That could be why adding the unconditional import into `numpy/random/__init__.py` helps, as it might make sure that `numpy/random/_pickle.py` gets fully-executed early before the deserialization happens. That would be a fragile fix, though, probably dependent on the precise mix of `gym` and `ray` objects that are being deserialized. I don't think it's a general solution.

**Comment by rkern** [comment]
@giuse Do you see a warning like this anywhere in your output?

```
2019-08-08 17:51:05,049 WARNING worker.py:352 -- WARNING: Falling back to serializing objects of type <class 'numpy.random.mtrand.RandomState'> by using pickle. This may be inefficient.
```

**Comment by rkern** [comment]
@giuse In this list `[ ev.evaluate.remote(ind) for ev, ind in zip(self.fitness_evaluators, population) ]`, which objects do you think hold the `RandomState`? `ev` or `ind`? Do you think it's just the `gym` `Space` object that is owning the `RandomState` that's causing the problem? 

```python
import numpy as np
import gym
import ray


class RandomAgent(object):
    """The world's simplest agent!"""
    def __init__(self, action_space):
        self.action_space = action_space

    def act(self, observation, reward, done):
        return self.action_space.sample()


@ray.remote
class Dummy(object):
    def evaluate(self, env):
        agent = RandomAgent(env.action_space)
        ob = env.reset()
        reward = 0
        done = False
        action = agent.act(ob, reward, done)
        ob, reward, done, _ = env.step(action)
        return reward


def main():
    ray.init(object_store_memory=1<<30)

    actor = Dummy.remote()
    env = gym.make('BipedalWalker-v2')
    env.seed(12345)
    print(ray.get(actor.evaluate.remote(env)))


if __name__ == '__main__':
    main()
```

**Comment by charris** [comment]
I pushed this off to 1.17.2. If folks feel there is nothing more for NumPy to do about this, please close the issue.

**Comment by charris** [comment]
@rkern @bashtage Should this be closed?

**Comment by bashtage** [comment]
I think so.  The issue is in how other modules are trying to guess that module list -- the module pickles fine.

**Comment by charris** [comment]
OK, closing this. If more information becomes available, please reopen.
