### ISSUE TITLE
Build error, OS X 10.11

### ISSUE THREAD

**Issue by toby5box** [numpy/numpy#14300]
I am unable to use the prebuilt binaries for numpy 1.17.0 (via scikit-image) because they result in Illegal instruction on my Mac Pro 2,1 (e.g. inside `probabilistic_hough_line()`).

However, a source build also fails. Is there some way I can change the architectural parameters so that it will build on my hardware? Under OS X 10.11.5.

### Reproducing command:

```
$ cat requirements.txt
cycler==0.10.0
decorator==4.3.0
imageio==2.3.0
kiwisolver==1.0.1
matplotlib==2.2.2
networkx==2.1
numpy==1.17.0
Pillow==4.3.0
pyparsing==2.2.0
python-dateutil==2.7.2
pytz==2018.4
PyWavelets==0.5.2
scikit-image==0.15.0
scipy==1.0.1
six==1.11.0
  $  pip install --force-reinstall --no-binary :all: scikit-image numpy
```

### Error message:

First few errors are quoted below.

```
    clang: build/src.macosx-10.11-x86_64-3.7/numpy/core/src/umath/loops.c
    clang: numpy/core/src/umath/umathmodule.c
    clang: numpy/core/src/umath/reduction.c
    In file included from numpy/core/src/umath/loops.c.src:47:
    numpy/core/src/umath/simd.inc.src:1287:12: warning: implicit declaration of function '_mm512_mask_i32gather_ps' is invalid in C99 [-Wimplicit-function-declaration]
        return _mm512_mask_i32gather_ps(src, kmask, vindex, addr, 4);
               ^
    numpy/core/src/umath/simd.inc.src:1287:12: error: returning 'int' from a function with incompatible result type '__m512' (vector of 16 'float' values)
        return _mm512_mask_i32gather_ps(src, kmask, vindex, addr, 4);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    numpy/core/src/umath/simd.inc.src:1305:12: warning: implicit declaration of function '_mm512_mask_mov_ps' is invalid in C99 [-Wimplicit-function-declaration]
        return _mm512_mask_mov_ps(x, ymask, y);
               ^
    numpy/core/src/umath/simd.inc.src:1305:12: error: returning 'int' from a function with incompatible result type '__m512' (vector of 16 'float' values)
        return _mm512_mask_mov_ps(x, ymask, y);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    numpy/core/src/umath/simd.inc.src:1311:26: warning: implicit declaration of function '_mm512_getexp_ps' is invalid in C99 [-Wimplicit-function-declaration]
        return _mm512_add_ps(_mm512_getexp_ps(x), _mm512_set1_ps(1.0f));
                             ^
    numpy/core/src/umath/simd.inc.src:1311:26: error: passing 'int' to parameter of incompatible type '__m512' (vector of 16 'float' values)
        return _mm512_add_ps(_mm512_getexp_ps(x), _mm512_set1_ps(1.0f));
                             ^~~~~~~~~~~~~~~~~~~
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0/include/avx512fintrin.h:419:22: note: passing argument to parameter '__a' here
    _mm512_add_ps(__m512 __a, __m512 __b)
                         ^
    In file included from numpy/core/src/umath/loops.c.src:47:
    numpy/core/src/umath/simd.inc.src:1317:12: warning: implicit declaration of function '_mm512_getmant_ps' is invalid in C99 [-Wimplicit-function-declaration]
        return _mm512_getmant_ps(x, _MM_MANT_NORM_p5_1, _MM_MANT_SIGN_src);
               ^
    numpy/core/src/umath/simd.inc.src:1317:33: error: use of undeclared identifier '_MM_MANT_NORM_p5_1'
```

**Comment by mattip** [comment]
It seems your machine is only partially supported, and your version of clang claims to support avx512f intrinsics but doesn't really.

You could try to disable `avx512f` by adding a `-march=skylake` flag to clang, (as opposed to `-march=skylake-avx512` which should force support).

Isn't that version of MacOS [past end-of-life](https://news.fnal.gov/2018/09/macos-el-capitan-v10-11-end-of-life-thursday-nov-1/), is it still receiving updates? Can you run in a docker with an updated OS/clang?

**Comment by matthew-brett** [comment]
@toby5box - can you say more about the problem with the pre-built binaries?  That should work.

**Comment by toby5box** [comment]
Prebuilt binaries produce an illegal instruction, I believe for the reason @mattip identified.

**Comment by toby5box** [comment]
@mattip Even with `-march=skylake`, these symbols are still configured in:

```
    #define HAVE_ATTRIBUTE_TARGET_AVX 1
    #define HAVE_ATTRIBUTE_TARGET_AVX2 1
    #define HAVE_ATTRIBUTE_TARGET_AVX512F 1
    #define HAVE_ATTRIBUTE_TARGET_AVX2_WITH_INTRINSICS 1
    #define HAVE_ATTRIBUTE_TARGET_AVX512F_WITH_INTRINSICS 1
```

Still looking for ways to prevent this.

This is probably the commit that broke everything for me: https://github.com/numpy/numpy/commit/bcf949bc3dfb873c09a37dbcfaaf018124d5517d

So I can also try an earlier version… (before `1.15.0rc1` I think?)

**Comment by toby5box** [comment]
I disabled the AVX2 and AVX512 symbols above, and built numpy 1.17.0. Still get the invalid instruction crash, though:

```
>>> import numpy as np
>>> from skimage.transform import hough_line, hough_line_peaks
from skimage.draw import line
img = np.zeros((15, 15), dtype=np.bool_)
rr, cc = line(0, 0, 14, 14)
img[rr, cc] = 1
rr, cc = line(0, 14, 14, 0)
img[cc, rr] = 1
hspace, angles, dists = hough_line(img)
hspace, angles, dists = hough_line_peaks(hspace, angles, dists)
len(angles)
>>> from skimage.draw import line
>>> img = np.zeros((15, 15), dtype=np.bool_)
>>> rr, cc = line(0, 0, 14, 14)
>>> img[rr, cc] = 1
>>> rr, cc = line(0, 14, 14, 0)
>>> img[cc, rr] = 1
>>> hspace, angles, dists = hough_line(img)
Process 93363 stopped
* thread #1: tid = 0xe7d447, 0x0000000109c0642f _hough_transform.cpython-37m-darwin.so`__pyx_pw_7skimage_9transform_16_hough_transform_5_hough_line + 1983, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x0000000109c0642f _hough_transform.cpython-37m-darwin.so`__pyx_pw_7skimage_9transform_16_hough_transform_5_hough_line + 1983
_hough_transform.cpython-37m-darwin.so`__pyx_pw_7skimage_9transform_16_hough_transform_5_hough_line:
->  0x109c0642f <+1983>: roundsd $0xa, %xmm0, %xmm0
    0x109c06435 <+1989>: cvttsd2si %xmm0, %r12
    0x109c0643a <+1994>: addq   %r12, %r12
    0x109c0643d <+1997>: decq   (%r13)
```

**Comment by charris** [comment]
Are you running in a virtual environment?

**Comment by toby5box** [comment]
> Are you running in a virtual environment?

At the moment I am trying to get it to work on the host. I have Docker in Virtualbox as a last resort (Docker-machine).

I was previously using numpy natively on this host, but something has changed and that version no longer builds. OS X is 10.11.5 (has not changed).

**Comment by toby5box** [comment]
OK Looks like `numpy` is innocent. The illegal instruction was prevented by building scikit-image with `-march=x86-64`.

Thanks everyone, sorry for false alarm
