### ISSUE TITLE
BUG: np.dtype(ctypes.c_voidp) no longer works

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#12416]
Regression introduced in #12380 

In 1.15.4

```python
>>> np.dtype(ctypes.c_voidp)
dtype('uint64')
```

After:

```python
>>> np.dtype(ctypes.c_voidp)
AttributeError: type object 'c_void_p' has no attribute '__ctype_be__'
```

It's not clear to me if returning `uint64` is the right thing to do, but it's definitely better than producing an AttributeError.

**Comment by mattip** [comment]
Closed by #12417
