### ISSUE TITLE
BUG: MaskedArray with nested dtype and object elements cause AttributeError on access

### ISSUE THREAD

**Issue by ttmapr** [numpy/numpy#15895]
When I create a `MaskedArray` using a nested dtype which contains an `object` at the innermost level, trying to access it causes an _AttributeError: 'str' object has no attribute 'ndim'_.

If I use `int` instead of `object`, the element access works fine.

The issue seems to be caused by the assumption that `_fill_value` is of a numpy type and has an `ndim` attribute.
This assumption is true for `numpy.int32` which would be used if `int` was specified inside the dtype.
But for `object`, the `_fill_value` will be a just python `str` _'?'_, which has no attribute `ndim`.

I propose to change the code line in question to
```python
if hasattr(dout._fill_value, 'ndim') and dout._fill_value.ndim > 0:
```

### Reproducing code example:

```python
import numpy as np
my_dtype = np.dtype([('b', [('c', object)], (1,))])
a = np.ma.masked_all((1,), my_dtype)
print(a['b']['c'])
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\numpy\ma\core.py", line 3276, in __getitem__
    if dout._fill_value.ndim > 0:
AttributeError: 'str' object has no attribute 'ndim'
```

### Numpy/Python version information:

1.18.1 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]

**Comment by vrakesh** [comment]
Nice catch

but shouldn't we just check if __fill_value is not a ```str``` rather than use hasattr. But even then it feels hacky, there seems to be a comment regarding issue #6723 above the check. 

is this the right approach @seberg ? Trying to understand the background better.

**Comment by seberg** [comment]
Well, its a bit of a mess. But aside from that, you are right of course. Checking for `ndim` has a bad code smell (and could definitely fail). Even the current code _can_ do something incorrect for certain `object` cases in theory.
I think the solution has to be to test for this happening more directly, one thing I am considering is changing it along:
```
new_fill_value = self._fill_value[indx, ...]  # guarantee array return
```
and moving the `flat` line out of the if. Or, alternative adding an `else: dout._fill_value = new_fill_value[()]`.

**Comment by eric-wieser** [comment]
So, the purpose of `_fill_value` was to _always_ be an array, unlike `.fill_value` which is the scalar.

Do we know how `_fill_value` is ending up with the wrong type?

**Comment by seberg** [comment]
Ah sorry, this is of course structured access, which is the problem (so the `...` suggestion will not work on its own). In any case, this code branch seems to not know about `_fill_value` being guaranteed to be an array, and it has to make sure of that.

Probably the best thing to do is to get the new dtype directly with `dtype = self._fill_value.dtype[indx]`, and then using `dtype.ndim` to check for that special branch and otherwise create a new empty array with that dtype and assign to it to ensure that the new `_fill_value` is again an array.

**Comment by vrakesh** [comment]
I have looked into the issue, a little more

I have a better understanding of masked array

The solution would be something like this
```python
                    if self._fill_value.dtype[indx].ndim > 0:
                        if not (dout._fill_value ==
                                dout._fill_value.flat[0]).all():
                            warnings.warn(
                                "Upon accessing multidimensional field "
                                f"{indx!s}, need to keep dimensionality "
                                "of fill_value at 0. Discarding "
                                "heterogeneous fill_value and setting "
                                f"all to {dout._fill_value[0]!s}.",
                                stacklevel=2)
                        dout._fill_value = dout._fill_value.flat[0]
                    else:
                        dout._fill_value = array(self._fill_value[indx])
```

**Comment by seberg** [comment]
Yeah, something along those lines, although I did not check carefully, and there may be some other tricky stuff lurking.
