### ISSUE TITLE
BUG: ppc64le build fails with cpu-baseline=none - VSX dispatch targets miss NPY_HAVE_VSX (vec_load_len implicit declaration)

### ISSUE THREAD

**Issue by supr** [numpy/numpy#31593]
### Describe the issue:

On ppc64le (little-endian POWER), building NumPy with `-Dcpu-baseline=none`
  fails to compile. The VSX dispatch-target sources error out with a cascade of:

  ../numpy/_core/src/common/simd/vec/memory.h:63:12: error: implicit declaration
    of function 'vec_load_len' [-Wimplicit-function-declaration]

  plus `vec_vsx_ld`, `vec_xl`, `vec_vsx_st`, `vec_xst`, `vec_extract`, and many
  `cannot convert a value of type 'int' to vector type ... which has different
  size` follow-ons.

  ### Root cause:

  `vec_load_len` is an **s390x/VX (zarch)** intrinsic, not a Power one. The SIMD
  code in `numpy/_core/src/common/simd/vec/memory.h` selects the right branch via
  `NPY_HAVE_VSX`:

  ```c
  #ifdef NPY_HAVE_VSX
      return vec_promote(*npyv__ptr2u64(ptr), 0);   // Power
  #else // VX
      return vec_load_len((const unsigned long long*)ptr, 7);  // s390x
  #endif

  NPY_HAVE_VSX is the generic "any VSX level" flag, and meson_cpu/main_config.h.in
  only includes <altivec.h> under #ifdef NPY_HAVE_VSX.

  With cpu-baseline=none, VSX2/VSX3/VSX4 are enabled only as dispatch targets.
  Each dispatch target is compiled in isolation with just its own
  -DNPY_HAVE_VSX2 (etc.) and not the implied -DNPY_HAVE_VSX. So on a Power
  build the #else // VX branch is wrongly taken and <altivec.h> is never
  included.

  The actual failing compile command (note -DNPY_HAVE_VSX2 but no
  -DNPY_HAVE_VSX):

  gcc ... -O3 -DNPY_HAVE_VSX2 ... -mcpu=power8 -DNPY_MTARGETS_CURRENT=VSX2 ...
      -c numpy/_core/.../loops_arithmetic.dispatch.c

  This is why default CI builds don't hit it: the default ppc64le baseline is VSX2,
  which defines NPY_HAVE_VSX project-wide via add_project_arguments, so dispatch
  targets inherit it. It only surfaces when the baseline doesn't already include VSX
  (e.g. distributors that set cpu-baseline=none for portable binaries — NixOS does
  this)

### Reproduce the code example:

```python
Minimal standalone reproducer (no NumPy build needed), mirroring npyv__loadl:

  #ifdef NPY_HAVE_VSX
  #  include <altivec.h>
  #endif
  typedef __vector unsigned long long npyv_u64;
  static npyv_u64 npyv__loadl(const void *ptr) {
  #ifdef NPY_HAVE_VSX
      return vec_promote(*(const unsigned long long*)ptr, 0);
  #else /* VX */
      return vec_load_len((const unsigned long long*)ptr, 7);
  #endif
  }
  int main(void){ unsigned long long x[2]={1,2}; npyv__loadl(x); return 0; }

  # fails — simulates a VSX2 dispatch target:
  $ gcc -O3 -mcpu=power8 -DNPY_HAVE_VSX2 -c repro.c
  repro.c: error: implicit declaration of function 'vec_load_len' ...

  # passes — with the implied base flag also defined:
  $ gcc -O3 -mcpu=power8 -DNPY_HAVE_VSX2 -DNPY_HAVE_VSX -c repro.c

  Or, full build: pip install . -Csetup-args=-Dcpu-baseline=none on ppc64le.
```

### Error message:

```shell
../numpy/_core/src/common/simd/vec/memory.h: In function 'npyv__loadl':
  ../numpy/_core/src/common/simd/vec/memory.h:63:12: error: implicit declaration
    of function 'vec_load_len' [-Wimplicit-function-declaration]
     63 |     return vec_load_len((const unsigned long long*)ptr, 7);
        |            ^~~~~~~~~~~~
  ... (vec_vsx_ld, vec_xl, vec_vsx_st, vec_xst, vec_extract, and
  "cannot convert a value of type 'int' to vector type" cascades)
```

### Python and NumPy Versions:

NumPy v2.4.4 (also present on main). Python 3.13.

### Runtime Environment:

ppc64le (little-endian, POWER9), Linux. GCC 15.2 and GCC 16.1 both reproduce.
  Build configured with -Dcpu-baseline=none -Dcpu-dispatch=max.

**Comment by seiko2plus** [comment]
That's a bit strange the whole header `numpy/_core/src/common/simd/vec/memory.h` should not be included if `NPY_HAVE_VSX2` is not defined.

https://github.com/numpy/numpy/blob/37d5d57f0037a1c28e9055b1448e187cd3e73176/numpy/_core/src/common/simd/simd.h#L82-L84

Have you tried to build with clean build dir? maybe a cache issue.

**Comment by seiko2plus** [comment]
Aha, so `NPY_HAVE_VSX2` is defined but the implied feature def `NPY_HAVE_VSX` is not. then its appear to me as meson bug.. let me take a quick look..

**Comment by supr** [comment]
Thank You @seiko2plus for taking a look at this, this bug was triggered when trying to bootstrap nix on fedora ppc64le, which as part of its functional testing suite, pulls down mercurial which in-turn pulls in numpy. When compiling numpy on ppc64le, mine is a Power9 processor, it fails the compile with the above error.
