### ISSUE TITLE
BUG: Type hints for dtype related functions regressed

### ISSUE THREAD

**Issue by albanD** [numpy/numpy#25147]
### Describe the issue:

When upgrading from 1.24.3 to 1.26, mypy is now failing to understand the type hints from dtype related functions.
Running with mypy 1.6.0

### Reproduce the code example:

```python
import numpy as np

A = np.random.rand(2, 3)
B = A.astype(np.float32)
reveal_type(A)
reveal_type(B)
```

### Error message:

```shell
1.24.3 output:

test.py:5:13: note: Revealed type is "numpy.ndarray[Any, numpy.dtype[numpy.floating[numpy._typing._64Bit]]]"
test:6:13: note: Revealed type is "numpy.ndarray[Any, numpy.dtype[numpy.floating[numpy._typing._32Bit]]]"
```

1.26.0 output:
```
test.py:4:5: error: Need type annotation for "B"  [var-annotated]
test.py:5:13: note: Revealed type is "numpy.ndarray[Any, numpy.dtype[numpy.floating[numpy._typing._64Bit]]]"
test.py:6:13: note: Revealed type is "numpy.ndarray[Any, numpy.dtype[Any]]"
```
```


### Runtime information:

>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.26.0
3.11.4+ (heads/3.11:f207b346d4, Jun 11 2023, 14:33:13) [GCC 12.3.1 20230508 (Red Hat 12.3.1-1)]
>>> print(numpy.show_runtime())
[{'numpy_version': '1.26.0',
  'python': '3.11.4+ (heads/3.11:f207b346d4, Jun 11 2023, 14:33:13) [GCC '
            '12.3.1 20230508 (Red Hat 12.3.1-1)]',
  'uname': uname_result(system='Linux', node='albandes-fedora-K2202N0104138', release='6.5.6-100.fc37.x86_64', version='#1 SMP PREEMPT_DYNAMIC Fri Oct  6 19:01:16 UTC 2023', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '/home/albandes/local/pytorch/3.11_debug_source_env/lib/python3.11/site-packages/numpy.libs/libopenblas64_p-r0-0cf96a72.3.23.dev.so',
  'internal_api': 'openblas',
  'num_threads': 20,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]
None


### Context for the issue:

This is making our lint fail when upgrading to latest numpy in PyTorch.

**Comment by mtsokol** [comment]
@albanD I think we could close this issue - in the 2.0.0b1 release revealed type for `B` is:
```
numpy.ndarray[Any, numpy.dtype[numpy.floating[numpy._typing._32Bit]]]
```

Also, there are reveal tests for `astype`: https://github.com/numpy/numpy/blob/56dab5053eedbd0a34b8c5aa8bf66c46a8b15cb5/numpy/typing/tests/data/reveal/ndarray_conversion.pyi#L39C44-L39C51

**Comment by albanD** [comment]
yep that works for me locally as well with the beta version! Thanks!
