### PR TITLE
BUG: ensure linspace works on object input.

### LINKED ISSUE #13089: Numpy 1.16 linspace fails for very large start stop values
### Reproducing code example:
The following corner case works correctly with numpy 1.15.4 but raises an error with numpy 1.16.2 
```python
import numpy as np
np.linspace(start = -9223372036854775809, stop = -9223372036854775809, num =1)
```

This was detected in a test with auto generated input using hypothesis to generate the input.

### Error message:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-aa8cbb862cf0> in <module>
----> 1 np.linspace(start = -9223372036854775809, stop = -9223372036854775809, num =1)

~\AppData\Local\Continuum\miniconda3\envs\qcodes\lib\site-packages\numpy\core\function_base.py in linspace(start, stop, num, endpoint, retstep, dtype, axis)
    141 
    142     delta = stop - start
--> 143     y = _nx.arange(0, num, dtype=dt).reshape((-1,) + (1,) * delta.ndim)
    144     # In-place multiplication y *= delta/div is faster, but prevents the multiplicant
    145     # from overriding what class is produced, and thus prevents, e.g. use of Quantities,

AttributeError: 'float' object has no attribute 'ndim'

```
### Numpy/Python version information:

1.16.2 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]

### Details
This seems to happen when the number used is sufficiently large end up being represented
as an object dtype.  This in turn means that delta will be a regular floating point number and not a numpy float. Therefore it does not have a `ndim` method. The 1.15 code looks different and does not require the `ndim` method to be defined. 

```python
type(np.asanyarray(-9223372036854775809))
dtype('O')
type(np.asanyarray(-9223372036854775809) * 1.0 - np.asanyarray(-9223372036854775809) *1.0)
float
```

### PR DESCRIPTION
**Pull request by mhvk**
As it was, the difference between stop and start was calculated and
it was assumed that that would be a numpy scalar or array. This is
not true for object input.

fixes #13089

### CODE REVIEW

File: numpy/core/tests/test_function_base.py [hunk 1]
```diff
@@ -362,3 +362,9 @@ def test_retstep(self):
                 assert_(isinstance(y, tuple) and len(y) == 2 and
                         len(y[0]) == num and isnan(y[1]),
                         'num={0}, endpoint={1}'.format(num, ept))
+
+    def test_object(self):
+        start = array(1, dtype='O')
+        stop = array(2, dtype='O')
+        y = linspace(start, stop, 3)
+        assert_array_equal(y, array([1., 1.5, 2.]))
```
Comment (charris) [inline numpy/core/tests/test_function_base.py]: Might check that the result is an object array.

Comment (charris) [reply numpy/core/tests/test_function_base.py]: Or should it be?

Comment (mhvk) [reply numpy/core/tests/test_function_base.py]: I had that test first, but it failed...  And It should, as the `start = asanyarray(start) * 1.0` turns it into a regular float. And for floats, one would expect an array.

Note that I'm not sure this is necessarily the best behaviour, since it means that for very large ints, as in the original issue (#13089), we'll get back floats that are identical. But I don't know how to solve those anyway, since they cannot hold fractions. In the end, I think this is not numpy's problem... But we can at least avoid raising unrelated error on object input...

Comment (charris) [reply numpy/core/tests/test_function_base.py]: OK, I hadn't checked, but was thinking of object arrays of high precision floats, mpmath or some such. Could be made to work, but not worth the trouble, those who need it can roll their own.

File: numpy/core/function_base.py [hunk 2]
```diff
@@ -140,7 +140,7 @@ def linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None,
         dtype = dt
 
     delta = stop - start
```
Comment (eric-wieser) [inline numpy/core/function_base.py]: Ideally you'd do this computation while forcing the result to be an array and not a scalar, which would work better for nested object arrays. Perhaps ufuncs should gain a `keeparray` argument for this...

File: numpy/core/tests/test_function_base.py (hunk 1 above)
Comment (charris) [reply numpy/core/tests/test_function_base.py]: Precision could be a problem even if the floats don't repeat because float precision decreases with amplitude. I remember having that problem with plot axis in single precision wavenumbers :) Maybe worth a note in the documentation at some point.

File: numpy/core/function_base.py (hunk 2 above)
Comment (mhvk) [reply numpy/core/function_base.py]: It may be simpler to change the current behaviour of ufuncs: array scalar plus array scalar should not decay to a regular scalar.

Comment (jenshnielsen) [reply numpy/core/function_base.py]: Isn't the problem in line 135 and 136.

```
In [21]: type(np.asanyarray(np.array(1))*1.0)
Out[21]: numpy.float64

In [22]: type(np.asanyarray(np.array(1, dtype='O'))*1.0)
Out[22]: float
```

Comment (mhvk) [reply numpy/core/function_base.py]: @jenshnielsen - indeed, you are right. the problem is earlier, though it is the same issue: that an array scalar is allowed to decay to a regular one.

**Review by eric-wieser — APPROVED** [review]
Ideal solutions aside, this is probably the best option available to us right now

**Comment by eric-wieser** [comment]
Here's a hack to call a ufunc without decaying:

```python
def call_no_decay(f, *args):
    max_ndim = max(ndim(a) for a in args)
    if max_ndim:
        return f(*args)
    else:
        return f(*args, where=np.array([True])[0,...]
```

Probably behaves poorly on duck-arrays though

**Comment by mhvk** [comment]
Had a look what actually does the change to a scalar and it is the call to `PyArray_Return` in the output wrapping (`_apply_array_wrap`).

**Comment by mattip** [comment]
Thanks @mhvk
