### ISSUE TITLE
BUG: keepdims keyword for np.average does not work in np version 1.21.5

### ISSUE THREAD

**Issue by MartinVerot** [numpy/numpy#24936]
### Describe the issue:

The `keepdims` option for `np.average` returns an error saying that keepdims is an unexpected keyword while it works for `np.mean`. As `np.mean` is simpler than `np.average`, we loose some functionality.

### Reproduce the code example:

```python
#!/usr/bin/env python3
import numpy as np

a = np.reshape(np.arange(4*5*6),(4,5,6))
avg_a =  np.mean(a,keepdims=True)
print(avg_a.shape)
avg_a =  np.average(a,keepdims=True)
print(avg_a.shape)
```

### Error message:

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_314664/3011695449.py in <module>
      4 avg_a =  np.mean(a,keepdims=True)
      5 print(avg_a.shape)
----> 6 avg_a =  np.average(a,keepdims=True)
      7 print(avg_a.shape)

<__array_function__ internals> in average(*args, **kwargs)

TypeError: _average_dispatcher() got an unexpected keyword argument 'keepdims'
```

### Runtime information:

1.21.5
3.9.13 (main, Aug 25 2022, 23:26:10) 
[GCC 11.2.0]

**Comment by seberg** [comment]
Thanks, but as documented, it was added in 1.23.
