### ISSUE TITLE
TYP:  Incompatible types in assignment in a for loop over integer array

### ISSUE THREAD

**Issue by pavoljuhas** [numpy/numpy#30848]
### Describe the issue:

After updating from numpy-2.3.5 to 2.4.2 the mypy-1.19.1 type checker started complaining about incompatible types in the for-loop example below.

Is this a bug or a desired behavior?

If desired behavior, I would expect the type checker to also flag `x = a[0]` which is allowed as is.

### Reproduce the code example:

```python
import numpy as np

x = 0   # x is inferred as int type
a = np.arange(5, dtype=int)
x = a[0]        # typecheck OK
for x in a:     # typecheck fails
    print(x)
```

### Error message:

```shell
t.py:6: error: Incompatible types in assignment (expression has type "signedinteger[_32Bit | _64Bit]", variable has type "int")  [assignment]
```

### Python and NumPy Versions:

Python 3.13.12 on Debian Linux
NumPy 2.4.2

### Type-checker version and settings:

mypy 1.19.1

Example was checked with `mypy myproblem.py` without any configuration settings.
I tried this in a fresh Python virtual environment with only the numpy and mypy packages installed.

### Additional typing packages.

Here is the output from `pip freeze`

```
librt==0.8.1
mypy==1.19.1
mypy_extensions==1.1.0
numpy==2.4.2
pathspec==1.0.4
setuptools==82.0.0
typing_extensions==4.15.0
```

**Comment by jorenham** [comment]
You're running into a limitation of mypy here, rather than an issue in NumPy. The example will be accepted by setting the following configuration options in your `mypy.ini` or mypy config in `pyproject.toml`:

```
local_partial_types = true
allow_redefinition_new = true
```

**Comment by jorenham** [comment]
You could also avoid reassigning different types to the name name, by removing the line `x = 0`

**Comment by pavoljuhas** [comment]
> You could also avoid reassigning different types to the name name, by removing the line `x = 0`

This was to highlight the issue - we have some code with sequence-index variable which can be assigned either an `int` or values from integer array.  I can work around this by casting the array as `Sequence[int]`.

Thank you for quick response and suggestions!
