### PR TITLE
ENH: Missing operator++() for enum type

### PR DESCRIPTION
**Pull request by juztamau5**
## Description

This is a cleanup commit broken out from https://github.com/numpy/numpy/pull/22545. When compiling with a c++ standard, the ++ operator is undefined for enum types. However, the standard is flexible enough to support general `+ 1` incrementation.

## How has this been tested?

When compiling with g++, the error was:

```
datetime.c:1063:9: error: no match for 'operator++' (operand type is 'NPY_DATETIMEUNIT')
  1063 |         ++unit;
       |         ^~~~~~
```

After applying the change, I ran the following code in my RISC-V Cartesi machine:

```python
import numpy as np
print(np.sqrt(2))
```

output:

```
1.4142135623730951
```

### CODE REVIEW

**Comment by seberg** [comment]
Thanks.  I am not super excited about the change, since I wonder if there isn't more to look at anyway if this should happen.  If anyone likes it, please just merge, otherwise I may just close it in a bit.

**Comment by seberg** [comment]
OK, thanks.  I am just going to close this even if it is maybe the right thing to do:  It seems like it can be done when C++ comes along to this part of the code.
