### ISSUE TITLE
numpy 1.12.0 seems to break f2py

### ISSUE THREAD

**Issue by 2sn** [numpy/numpy#8479]
I now get lots of output of the form

```
(...)
/tmp/tmp8i0j4nc_/src.linux-x86_64-3.6/_keplermodule.c: At top level:
/tmp/tmp8i0j4nc_/src.linux-x86_64-3.6/_keplermodule.c:1052:21: error: expected expression before â,â token
   {"namezone",2,{{++,8}},NPY_CHAR},
                     ^
//tmp/tmp8i0j4nc_/src.linux-x86_64-3.6/_keplermodule.c:2468:15: note: (near initialization for âf2py_vars_def[848].dims.d[0]â)
/tmp/tmp8i0j4nc_/src.linux-x86_64-3.6/_keplermodule.c:2474:18: error: expected expression before â,â token
   {"ionbmax",2,{{,8}},NPY_CHAR},
                  ^
/tmp/tmp8i0j4nc_/src.linux-x86_64-3.6/_keplermodule.c:2474:18: error: initializer element is not constant
/tmp/tmp8i0j4nc_/src.linux-x86_64-3.6/_keplermodule.c:2474:18: note: (near initialization for âf2py_vars_def[854].dims.d[0]â)
/tmp/tmp8i0j4nc_/src.linux-x86_64-3.6/_keplermodule.c:2501:15: error: invalid type argument of unary â*â (have âintâ)
   {"dbuf",1,{{*(+2)}},NPY_DOUBLE},
               ^~~~~
/tmp/tmp8i0j4nc_/src.linux-x86_64-3.6/_keplermodule.c:2501:15: error: initializer element is not constant
   {"dbuf",1,{{*(+2)}},NPY_DOUBLE},
               ^
/tmp/tmp8i0j4nc_/src.linux-x86_64-3.6/_keplermodule.c:2501:15: note: (near initialization for âf2py_vars_def[881].dims.d[0]â)
/tmp/tmp8i0j4nc_/src.linux-x86_64-3.6/_keplermodule.c:2503:18: error: expected expression before â}â token
   {"ppnold",1,{{*}},NPY_DOUBLE},
                  ^
/tmp/tmp8i0j4nc_/src.linux-x86_64-3.6/_keplermodule.c:1667:19: error: wrong type argument to unary minus
   {"idumhead",1,{{-}},NPY_INT},
                   ^
/tmp/tmp8i0j4nc_/src.linux-x86_64-3.6/_keplermodule.c:3547:14: note: (near initialization for âf2py_zbrn_def[13].dims.d[0]â)
/tmp/tmp8i0j4nc_/src.linux-x86_64-3.6/_keplermodule.c:3699:19: error: expected expression before â,â token
   {"uuidhist",3,{{,,16}},NPY_CHAR},
                   ^
(...)
error: Command "gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/tmp/tmpgnfiujz_/src.linux-x86_64-3.6 -I/home/alex/Python/lib/python3.6/site-packages/numpy/core/include -I/home/alex/Python/include/python3.6m -c /tmp/tmpgnfiujz_/src.linux-x86_64-3.6/_keplermodule.c -o /tmp/tmpgnfiujz_/tmp/tmpgnfiujz_/src.linux-x86_64-3.6/_keplermodule.o" failed with exit status 1
```

in f2py in NumPy version 1.12.0 from PyPi and I can no longer compile the code.  For comparison, all worked fine in NumPy 1.11.3.

I am using Python 3.6.0, compiled with optimisation from the sources on Python.org on Fedora 25, gcc version 6.3.1 20161221 (Red Hat 6.3.1-1).

Seems to me something in the parsing is no longer working, not sure about the origin of all the special characters in the output either.

**Comment by rgommers** [comment]
Can you share the Fortran source?

**Comment by 2sn** [comment]
The FORTRAN code of this project is too big to be useful.
I would have to make an isolated test case, but was hoping there is something that may pop up immediately wheb the f2py code from 1.11.3 and 1.12.0 is compared.

**Comment by pv** [comment]
If it's a general issue that always occurs, it should have been already 
noticed in prereleases. A possibility is that this is Python 3.6 only, 
but also then there's the f2py test suite which presumably does not 
catch it.

**Comment by juliantaylor** [comment]
can you bisect numpy to get the commit that caused it? might be an easier first step to finding the issue from your big source.

**Comment by 2sn** [comment]
No, I have the same trouble with python 3.5.2 using numpy 1.12.0 whereas 1.11.3 works and all ese is the same.  It uniquely seems to be the upgraded numpy version.

**Comment by pv** [comment]
A number of f2py-using codebases work for me with Numpy 1.12.0, so 
what's broken is probably some feature that does not appear in them.
.
There are only a few changes in f2py, d0eea4a784ac23 and 
d156cafb3b9163d73 look most likely.

**Comment by 2sn** [comment]
yes, it seems they are all related to character arrays

```NPY_CHAR```

something of the format

```
      INTEGER, PARAMETER :: int32 = SELECTED_INT_KIND(8)
      integer(kind=int32), parameter :: ntdatv = 52
      character*10
     &     unittime(ntdatv)
      common/namecom/
     &     unittime
```

**Comment by pv** [comment]
Or, it's due to parsing of PARAMETERs. Minimal repro:
```
! foo.f90
! f2py -c foo.f90
subroutine foo(x)
       integer, parameter :: k = 52
       integer x(k)
end subroutine
```
So d0eea4a784a is possibly at fault.

**Comment by DeadParrot** [comment]
f2py is also broken in Python 2.7.12 and it looks like it is indeed due to PARAMETER parsing. Lines in the generated pyf that used to look like this:
`double precision dimension(278,9) :: elox`
now look like this:
`double precision dimension(,) :: elox`
when the array dimensions are PARAMETERs. I get a bunch of warnings about the PARAMETER processing like:
"can't multiply sequence by non-int of type 'str'" in evaluating 'mxx*mxy'
"cannot concatenate 'str' and 'int' objects" in evaluating 'ng+3'
"unsupported operand type(s) for -: 'str' and 'int'" in evaluating 'int((np-3)/2)'

**Comment by charris** [comment]
Should be fixed by #8494. Please reopen if there is still a problem.

**Comment by DeadParrot** [comment]
[1.12.1rc1](https://github.com/numpy/numpy/releases/tag/v1.12.1rc1) seems to do the trick. Thanks!
