### ISSUE TITLE
cant install on python 3.8b1 on windows

### ISSUE THREAD

**Issue by NewUserHa** [numpy/numpy#13790]
pip install numpy

```
numpy\random\mtrand\mtrand.c(40364): error C2198: 'PyCode_New': too few arguments for call
```

**Comment by mattip** [comment]
Did you use cython 0.29.10 which should fix that?

**Comment by jdemeyer** [comment]
> Did you use cython 0.29.10 which should fix that?

Cython is run by the maintainer when packaging numpy, not when installing numpy. So the proper fix is making a new numpy release generated by the latest Cython.

There is some discussion happening at https://bugs.python.org/issue37221 and https://bugs.python.org/issue37250 which may lead to a fix in CPython such that older Cython-generated code will continue working with Python 3.8. I'm in favor of that, but it's not clear whether that will be accepted.

**Comment by NewUserHa** [comment]
it is 0.29.10

**Comment by rgommers** [comment]
> Cython is run by the maintainer when packaging numpy, not when installing numpy. So the proper fix is making a new numpy release generated by the latest Cython.

This is happening a lot recently. I think the improvements to the packaging system make build-time requirements work in an acceptable fashion over the last year finally, so it may be time to consider shipping an sdist without generated sources. There are downsides too, but it's a discussion that would make sense to have.
