### ISSUE TITLE
Computing max relative error on obj-type arrays raises wrong type of exception

### ISSUE THREAD

**Issue by brianwa84** [numpy/numpy#14323]
The special casing in https://github.com/numpy/numpy/pull/13642 which attempts to resolve https://github.com/numpy/numpy/issues/12942 (backported to 1.16.4 by https://github.com/numpy/numpy/pull/13644) seems not quite resolved.

### Reproducing code example:

```python
import numpy as np
try:
      np.testing.assert_array_equal(
          np.array(4739637422259008171279111936565847718172840333659989346110031848462024409325843520672034019682419018756694789209060374729378903341235995191814327794100193),
          np.array(1853511932515157830145718229839389604002696738326084298784104830898674005586744314129661322485102036650701917909364894585809076071785405224020363172866907))
except AssertionError:
      pass
```

### Error message:

```
  File "numpy/testing/_private/utils.py", line 904, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "numpy/testing/_private/utils.py", line 803, in assert_array_compare
    max_abs_error = error.max()
AttributeError: 'int' object has no attribute 'max'
```
 

### Numpy/Python version information:

```
Running tests under Python 3.6.7: embedded.
1.16.4 3.6.7 (default, redacted, redacted) 
[GCC Clang google3-trunk (trunk r367622)]
```

**Comment by eric-wieser** [comment]
This worked fine in 1.15.4

**Comment by eric-wieser** [comment]
replacing `error.max()` with `np.max(error)` would probably fix this.

**Comment by mattip** [comment]
This passes on master
