### ISSUE TITLE
np.__config__.mkl_info missing in 1.17?

### ISSUE THREAD

**Issue by njzjz** [numpy/numpy#14751]
### Reproducing code example:

```python
import numpy as np
print(np.__config__.mkl_info)
```

### Error message:
`AttributeError: module 'numpy.__config__' has no attribute 'mkl_info'`

### Numpy/Python version information:

```
1.17.2 3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0]
```
And it's an anaconda's numpy. I am not sure whether it is caused by numpy or anaconda. It worked well in 1.16.

**Comment by mattip** [comment]
I am not sure `__config__` is public, it is not included in `np.__all__`. It is exposed via  `np.show_config` which is actually `np.__config__.show`.

The only methods in `__config__.all__` are `["get_info", "show"]`.  `np.__config__.get_info('mkl_info')` on my system returns `{}`. Are you looking for `blas_mkl_info` and `lapack_mkl_info` which I think are the "official" info classes and should be filled in if `mkl` is present?

**Comment by njzjz** [comment]
I want check whether the numpy is built by mkl in my program. `'mkl_rt' in np.__config__.get_info("blas_mkl_info")['libraries']` returns `True`. Is it a recommended way to check the build information?

**Comment by 1ap** [comment]
To see whether it is would be mkl or openblas, check the output of  `np.__config__.blas_info`.
