### ISSUE TITLE
BUG: Install Error for 1.14.4 on PPC64le/Altivec Type Vector

### ISSUE THREAD

**Issue by ax3l** [numpy/numpy#24673]
### Describe the issue:

I am installing numpy 1.24.4 with clang 12.0.1 on  ppc64le.

This error is raised:
```
      INFO: clang: build/src.linux-ppc64le-3.8/numpy/core/src/umath/loops_exponent_log.dispatch.c
      In file included from numpy/core/src/multiarray/argfunc.dispatch.c.src:12:
      In file included from numpy/core/src/common/simd/simd.h:15:
      In file included from numpy/core/src/common/npy_cpu_dispatch.h:36:
      In file included from build/src.linux-ppc64le-3.8/numpy/distutils/include/npy_cpu_dispatch_config.h:19:
      /usr/tce/packages/clang/clang-12.0.1/release/lib/clang/12.0.1/include/altivec.h:55:19: error: unknown type name 'vector'
      static __inline__ vector bool char __ATTRS_o_ai
                        ^
      /usr/tce/packages/clang/clang-12.0.1/release/lib/clang/12.0.1/include/altivec.h:56:10: error: unknown type name 'vector'
      vec_perm(vector bool char __a, vector bool char __b, vector unsigned char __c);
               ^
      /usr/tce/packages/clang/clang-12.0.1/release/lib/clang/12.0.1/include/altivec.h:56:32: error: unknown type name 'vector'
      vec_perm(vector bool char __a, vector bool char __b, vector unsigned char __c);
                                     ^
      /usr/tce/packages/clang/clang-12.0.1/release/lib/clang/12.0.1/include/altivec.h:66:19: error: unknown type name 'vector'
      static __inline__ vector bool short __ATTRS_o_ai vec_perm(
                        ^
      /usr/tce/packages/clang/clang-12.0.1/release/lib/clang/12.0.1/include/altivec.h:67:5: error: unknown type name 'vector'
          vector bool short __a, vector bool short __b, vector unsigned char __c);
          ^
      /usr/tce/packages/clang/clang-12.0.1/release/lib/clang/12.0.1/include/altivec.h:67:28: error: unknown type name 'vector'
          vector bool short __a, vector bool short __b, vector unsigned char __c);
                                 ^
```

### Reproduce the code example:

```python
On a ppc64le RHEL8 machine:

python3 -m pip install numpy
```
```


### Error message:

_No response_

### Runtime information:

- RHEL8
- Python version: 3.8

### Context for the issue:

I am compiling numpy as part of our software stack on Summit (OLCF) and Lassen (LLNL) supercomputers.

**Comment by ax3l** [comment]
Full log: [numpy.txt](https://github.com/numpy/numpy/files/12563892/numpy.txt)

**Comment by ax3l** [comment]
I see the error also in versions:
- 1.23

It compiles with this version:
- 1.22

**Comment by ax3l** [comment]
GCC 11.2.1 for numpy 1.14 has the same problem in my tests.

Note: best to focus on GCC for this fix, there might be problems with Clang 12 and its Altivec support.
Similar issues seen in PyTorch vectorization: https://github.com/pytorch/pytorch/issues/108934

**Comment by ax3l** [comment]
GCC 11.2.1 compiles with numpy 1.24 in my tests.

Due to the linked Clang issues with Altivec, I will close this as probably a compiler toolchain issue with Clang/LLVM for Altivec.
