### PR TITLE
BLD: Modify cpu detection and printing to get working aarch64 build 

### LINKED ISSUE #11564: NumPy fails to build on aarch64
The master branch currently fails to build on aarch64/ARMv8 with the following:

```
aarch64-linux-gnu-gcc: numpy/core/src/npymath/ieee754.c
In file included from numpy/core/src/private/npy_config.h:6:0,
                 from numpy/core/src/npymath/npy_math_common.h:8,
                 from numpy/core/src/npymath/ieee754.c.src:7:
numpy/core/include/numpy/npy_cpu.h:106:6: error: #error Unknown CPU, please report this to numpy maintainers with information about your platform (OS, CPU and compiler)
     #error Unknown CPU, please report this to numpy maintainers with \
      ^
In file included from numpy/core/src/private/npy_config.h:6:0,
                 from numpy/core/src/npymath/npy_math_common.h:8,
                 from numpy/core/src/npymath/ieee754.c.src:7:
numpy/core/include/numpy/npy_cpu.h:106:6: error: #error Unknown CPU, please report this to numpy maintainers with information about your platform (OS, CPU and compiler)
     #error Unknown CPU, please report this to numpy maintainers with \
      ^
error: Command "aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Inumpy/core/src/npymath -Inumpy/core/include -Inumpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python3.5m -Inumpy/core/src/private -Inumpy/core/src/npymath -Inumpy/core/src/private -Inumpy/core/src/npymath -Inumpy/core/src/private -Inumpy/core/src/npymath -c numpy/core/src/npymath/ieee754.c -o build/temp.linux-aarch64-3.5/numpy/core/src/npymath/ieee754.o -MMD -MF build/temp.linux-aarch64-3.5/numpy/core/src/npymath/ieee754.o.d" failed with exit status 1
```

I believe this is a result of the new detection logic introduced in #11016.  It seems as if `__arm__` and `__ARMEL__` may not be defined on some? aarch64 platforms.  Rather it may be necessary to use `__aarch64__` and `__AARCH64EL__`.

### PR DESCRIPTION
**Pull request by ksunden**
Closes #11564

### CODE REVIEW

**Comment by jjhelmus** [comment]
Once the build is working again on aarch64 we could use the new ARMv8-A on [Shippable](http://blog.shippable.com/shippable-arm-packet-deliver-native-ci-cd-for-arm-architecture) for an altarch CI.

**Comment by charris** [comment]
LGTM failure looks unrelated.

**Comment by charris** [comment]
Has this been tested to see if it fixes the build?

File: numpy/core/src/multiarray/dragon4.c [hunk 1]
```diff
@@ -2714,7 +2714,7 @@ Dragon4_PrintFloat_Intel_extended128(
  * becomes more common.
  */
 static npy_uint32
-Dragon4_PrintFloat_IEEE_binary128(
+Dragon4_PrintFloat_IEEE_binary128_le(
```
[the remark this answers is not in the document]
Comment (charris) [reply numpy/core/src/multiarray/dragon4.c]: This function is for quad precision floats, I doubt that ARM implements that.

[the remark this answers is not in the document]
Comment (ksunden) [reply numpy/core/src/multiarray/dragon4.c]: Without this change, I got warnings for implicit definition of `Dragon4_PrintFloat_IEEE_binary128_le` and unused symbol for `Dragon4_PrintFloat_IEEE_binary128`

Additionally, it failed on import looking for `Dragon4_PrintFloat_IEEE_binary128_le`

It is very possible that the root cause is actually the identification of what representation it should be using. I've been looking at https://github.com/numpy/numpy/blob/20a80e08a9031cc6c69b168a0988443d15b8101f/numpy/core/setup_common.py#L343 to see if there's something incorrect there.

I've created the object file outside of running setup_common, and confirmed that the sequence that identifies IEEE_QUAD_LE is indeed present in the `od -b` dump

[the remark this answers is not in the document]
Comment (ksunden) [reply numpy/core/src/multiarray/dragon4.c]: Given the error that was thrown, I tried the naive approach of just editing the function name, not fully expecting it to work, but it did (at least as far as building was concerned, still have some test failures)

[the remark this answers is not in the document]
Comment (charris) [reply numpy/core/src/multiarray/dragon4.c]: Hmm, LLVM does seem to have software support for quad precision, so I think we need to track this down. What is your compiler tool change. I'm concerned about the endian part. @ahaldane Comment?

[the remark this answers is not in the document]
Comment (charris) [reply numpy/core/src/multiarray/dragon4.c]: The use of quad precision seems to depend on a compiler flag, `-mfloat128`. I don't know what the default value is.

[the remark this answers is not in the document]
Comment (jjhelmus) [reply numpy/core/src/multiarray/dragon4.c]: `-mfloat128` does not seem to be a valid option on aarch64 but is available for ppc64le

[the remark this answers is not in the document]
Comment (ksunden) [reply numpy/core/src/multiarray/dragon4.c]:
```bash
$ gcc --version
gcc (Debian 7.3.0-24) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE
```

```bash
$ uname -a
Linux localhost 3.18.0-17554-g9194949d4df2 #1 SMP PREEMPT Fri Jun 22 17:45:52 PDT 2018 aarch64 GNU/Linux
```

My machine is a little endian aarch64 chromebook

[the remark this answers is not in the document]
Comment (charris) [reply numpy/core/src/multiarray/dragon4.c]: Maybe wrong flag, but it is there somewhere, https://llvm.org/docs/LangRef.html#floating-point-types. We should be detecting on the byte representation, so either there is an error in that or the compiler is actually producing quad floats.

**Comment by charris** [comment]
The availability of half precision is also interesting.

**Comment by ksunden** [comment]
I have indeed built this on my machine, and @jjhelmus has built it as well on a remote machine

**Comment by charris** [comment]
Out of curiosity, what does `np.finfo(np.float128)` show?

**Comment by ksunden** [comment]
```python
>>> np.finfo(np.float128)
finfo(resolution=1e-33, min=-1.189731495357231765085759326628007e+4932, max=1.189731495357231765085759326628007e+4932, dtype=float128)
```

**Comment by charris** [comment]
OK, looks like genuine IEEE quad precision long doubles, the `finfo` function should be making the identification based on the byte representation. It would be interesting to know *why* they are there, as that seems not to be common news, but the signs and portents do seem to indicate that the long delayed move to quad precision is about to get underway.

File: numpy/core/src/multiarray/dragon4.c (hunk 1 above)
[the remark this answers is not in the document]
Comment (charris) [reply numpy/core/src/multiarray/dragon4.c]: OK we need to have two functions, one with the `_be` extension and one with the `_le` extension. This function, despite the comment, looks to be big endian with the little endian version in #11570. The difference is only four lines, so it would be nice to have wrappers for the endian specific versions that called into the common code, but the easy fix would be copy the function from # 11570 here with the appropriate name.

[the remark this answers is not in the document]
Comment (charris) [reply numpy/core/src/multiarray/dragon4.c]: See similar wrappers for the various extended precision alignments.

[the remark this answers is not in the document]
Comment (charris) [reply numpy/core/src/multiarray/dragon4.c]: I think all the wrappers need to do is swap the a and b members of buf128, so maybe only one wrapper to do that for the `_le` version and name this function with the `_be` extension.

[the remark this answers is not in the document]
Comment (ksunden) [reply numpy/core/src/multiarray/dragon4.c]: I've pushed the easy fix, cherry-picking the commit from my other PR, I'll work on the wrapper func now

**Comment by QuLogic** [comment]
`BigInt_Set_2x_uint64` is also not defined for `HAVE_LDOUBLE_IEEE_QUAD_BE`.
