### ISSUE TITLE
TYP: np.dtype.type(value) no longer type-checking since numpy==2.3.4

### ISSUE THREAD

**Issue by bersbersbers** [numpy/numpy#29977]
### Describe the issue:

In `numpy==2.3.3`, the following code runs in Python and type-checks.

In `numpy==2.3.4`, the same code runs in Python but fails type-checks.

### Reproduce the code example:

```python
from typing import Any

import numpy as np

def print_typed_one(my_type: np.dtype[np.integer[Any]]) -> None:
    print(my_type.type(1))

print_typed_one(np.dtype("=i1"))
```

### Error message:

```shell
bug.py:6: error: Too many arguments for "integer"  [call-arg]
bug.py:6: note: See https://mypy.rtfd.io/en/stable/_refs.html#code-call-arg for more info
Found 1 error in 1 file (checked 1 source file)

and

bug.py
  bug.py:6:24 - error: Expected 0 positional arguments (reportCallIssue)
1 error, 0 warnings, 0 informations
```

### Python and NumPy Versions:

Python 3.13.8
numpy 2.3.4

### Type-checker version and settings:

mypy 1.18.2
pyright 1.1.406

**Comment by jorenham** [comment]
This was an intentional choice. The `np.integer` type is abstract, so trying to call it will raise a `TypeError` at runtime.

```py
>>> import numpy as np
>>> np.integer(1)
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    np.integer(1)
    ~~~~~~~~~~^^^
TypeError: cannot create 'numpy.integer' instances
```

**Comment by bersbersbers** [comment]
I see, and I don't :)

First, I updated the original post - `dtype` is not actually required at all.

Then, I understand you want to avoid `np.integer(1)`. But that already failed type-checking in numpy 2.3.3:

```python
import numpy as np

np.integer(1)
```

gives in `mypy`:
```
bug.py:3: error: Cannot instantiate abstract class "integer" with abstract attribute "__init__"  [abstract]
bug.py:3: note: See https://mypy.rtfd.io/en/stable/_refs.html#code-abstract for more info
Found 1 error in 1 file (checked 1 source file)
```

Similarly, passing `np.integer` to my function did not work in 2.3.3, either:

```python
from typing import Any

import numpy as np

def print_typed_one(my_type: type[np.integer[Any]]) -> None:
    print(my_type(1))

print_typed_one(np.integer)
```

gives
```
bug.py:8: error: Only concrete class can be given where "type[integer[Any]]" is expected  [type-abstract]
bug.py:8: note: See https://mypy.rtfd.io/en/stable/_refs.html#code-type-abstract for more info
Found 1 error in 1 file (checked 1 source file)
```

I cannot find a way that type-checks yet runs into the runtime behavior your describe.

So I wonder what prompted this change from 2.3.3 to 2.3.4, understanding that it prevents a valid use case (see my original post) while doubling-down on an invalid case that did not work before (passing/using `np.integer`).

**Comment by jorenham** [comment]
> So I wonder what prompted this change from 2.3.3 to 2.3.4

If I remember correctly, stubtest started complaining about the `integer` constructor being incorrect after I upgraded to mypy 1.18. I first thought it was a false positive, but after a little digging, it turned out that the constructor was indeed incorrect.
So, after a detour through numtype (which has stricter type-checking than numpy), I opened #29629, which changes the constructor signature of `integer`. And as you can see in this IPython output, it agrees with runtime signature:

```python
In [1]: np.__version__
Out[1]: '2.3.4'

In [2]: np.integer?
Init signature: np.integer()  # 👈🏻 
Docstring:      Abstract base class of all integer scalar types.
File:           ~/.local/share/uv/tools/ipython/lib/python3.14/site-packages/numpy/__init__.py
Type:           type
Subclasses:     signedinteger, unsignedinteger
```

As you can also see in #29629, this caused an issue in xarray that's pretty similar to this one. But since that error was technically speaking a true positive, i.e. a type-unsafe situation, I thought of that as a good thing.

But now you're showing me this, I agree that this is a pretty annoying situation that has no good solution. 

So even though the stubs are more accurate this way, the increase in type-safety might not have been worth it, after all, and I'm tempted to (partially) revert it.

Do you think that restoring the (non-existent) `integer.__new__` parameter will fix your issue? 
https://github.com/numpy/numpy/blob/279c07e80edc0a73de7edc3532621569f47f39c8/numpy/__init__.pyi#L4279-L4281

**Comment by bersbersbers** [comment]
Wow, thanks for this long explanation! I must admit `__new__` vs. `__init__` has never been a concern for me, so I can basically follow but don't see all the implications.

> Do you think that restoring the (non-existent) integer.__new__ parameter will fix your issue?

Do you mean
```python
    @abstractmethod
    def __init__(self, value: _ConvertibleToInt = ..., /) -> None: ...
```

If I add (only) that, I get

> bug.py:10: error: Only concrete class can be given where "type[integer[Any]]" is expected  [type-abstract]

(I guess) because `np.uint8` now is abstract, too - it probably would need to implement `__init__`, too. (I did not test this.)

I also came across https://github.com/python/mypy/issues/4717 which seems to imply that the safeguard I refer to in https://github.com/numpy/numpy/issues/29977#issuecomment-3409290693 (preventing `np.integer` from being passed to `print_typed_one`) may not be forever.

So ultimately, I see it's a hard problem and I leave the decision up to you. I'll be happy when my example code above type checks, but I can live with a `# type: ignore` for this case as well.

**Comment by jorenham** [comment]
> > bug.py:10: error: Only concrete class can be given where "type[integer[Any]]" is expected  [type-abstract]
> 
> (I guess) because `np.uint8` now is abstract, too - it probably would need to implement `__init__`, too. (I did not test this.)

Hmmm, then we'd also have to add a non-abstract `__new__` to the `unsignedinteger` and `signedinteger` classes. But then type-checkers won't complain anymore when you do `signedinteger()`, which isn't ideal.

The better alternative would be to turn all `np.int*`  and `np.uint*` types into concrete subclasses. For that, we would have to wait until the `numpy.typing.NBitBase` deprecation is expired though. And even so, it would be a breaking change, because things like `x: np.int8 = np.integer[Any]` will no longer be accepted then.

> I also came across [python/mypy#4717](https://github.com/python/mypy/issues/4717) which seems to imply that the safeguard I refer to in [#29977 (comment)](https://github.com/numpy/numpy/issues/29977#issuecomment-3409290693) (preventing `np.integer` from being passed to `print_typed_one`) may not be forever.

Yea, it's true that the way we use `@abstractmethod` here is a bit of a hack. But we can't turn `integer` into an actual `abc.ABC`, because, well, it isn't.
I was hoping that by removing the `__new__` parameter, we would be able to move away from this hack. But clearly that's not the way to go here.

So I think that the least painful route here is to sacrifice some of type-safety (i.e. introduce false negatives) in order to avoid these false-positives. 

---

Would you like to work on this yourself, or should I?

**Comment by bersbersbers** [comment]
> Would you like to work on this yourself

Thanks for the offer, but - not really ;) I cannot justify the effort for this single-line use case of mine, unfortunately.

**Comment by jorenham** [comment]
This will be addressed in the next NumPy release (2.3.5 or 2.4.0, whichever comes first)
