### PR TITLE
BUG: Fix compilation of halffloat with gcc 13.1

### LINKED ISSUE #23689: NumPy main fails to compile with gcc 13.1 on fedora 37
Gcc 13.1 compiles the maintenance/1.24.x branch, but fails with main. The problem file looks to be `numpy/core/src/npymath/halffloat.cpp`. There is no error message, the compilation just fails and the build exits, no other files are built after that. Note that gcc 12 compiles the main branch with no problems. I'm looking for suggestions on how to track this down, in particular, how to get more information from the failure.

build error:

```Bash
In file included from numpy/core/src/common/common.hpp:9,
                 from numpy/core/src/npymath/halffloat.cpp:12:
numpy/core/src/common/npstd.hpp:23:12: error: ‘uint8_t’ has not been declared in ‘std’
   23 | using std::uint8_t;
      |            ^~~~~~~
numpy/core/src/common/npstd.hpp:24:12: error: ‘int8_t’ has not been declared in ‘std’
   24 | using std::int8_t;
      |            ^~~~~~
numpy/core/src/common/npstd.hpp:25:12: error: ‘uint16_t’ has not been declared in ‘std’
   25 | using std::uint16_t;
      |            ^~~~~~~~
numpy/core/src/common/npstd.hpp:26:12: error: ‘int16_t’ has not been declared in ‘std’
   26 | using std::int16_t;
      |            ^~~~~~~
numpy/core/src/common/npstd.hpp:27:12: error: ‘uint32_t’ has not been declared in ‘std’
   27 | using std::uint32_t;
      |            ^~~~~~~~
numpy/core/src/common/npstd.hpp:28:12: error: ‘int32_t’ has not been declared in ‘std’
   28 | using std::int32_t;
      |            ^~~~~~~
numpy/core/src/common/npstd.hpp:29:12: error: ‘uint64_t’ has not been declared in ‘std’
   29 | using std::uint64_t;
      |            ^~~~~~~~
numpy/core/src/common/npstd.hpp:30:12: error: ‘int64_t’ has not been declared in ‘std’
   30 | using std::int64_t;
      |            ^~~~~~~
numpy/core/src/common/npstd.hpp:31:12: error: ‘uintptr_t’ has not been declared in ‘std’
   31 | using std::uintptr_t;
      |            ^~~~~~~~~
numpy/core/src/common/npstd.hpp:32:12: error: ‘intptr_t’ has not been declared in ‘std’
   32 | using std::intptr_t;
      |            ^~~~~~~~
numpy/core/src/common/npstd.hpp:34:12: error: ‘uint_fast16_t’ has not been declared in ‘std’
   34 | using std::uint_fast16_t;
      |            ^~~~~~~~~~~~~
numpy/core/src/common/npstd.hpp:35:12
```

### PR DESCRIPTION
**Pull request by seiko2plus**
closes #23689

### CODE REVIEW

**Comment by seberg** [comment]
Just to confirm, this is simply that our CI didn't have hardware that would run into it?

**Comment by seiko2plus** [comment]
> Just to confirm, this is simply that our CI didn't have hardware that would run into it?

No, it just matter of GCC compiler.

File: numpy/core/src/common/half.hpp [hunk 1]
```diff
@@ -72,7 +72,7 @@ class Half final {
     {
     #if defined(NPY_HAVE_AVX512FP16)
         __m128d md = _mm_load_sd(&f);
-        bits_ = static_cast<uint16_t>(_mm_cvtsi128_si32(_mm_castph_si128(_mm_cvtpd_ph(mf))));
+        bits_ = static_cast<uint16_t>(_mm_cvtsi128_si32(_mm_castph_si128(_mm_cvtpd_ph(md))));
```
Comment (seberg) [inline numpy/core/src/common/half.hpp:75]: Ah, nvm. I guess this is a fix unrelated to the issue...

Comment (seiko2plus) [reply numpy/core/src/common/half.hpp:75]: `NPY_HAVE_AVX512FP16/NPY_HAVE_AVX512_SPR` seems to only supported by gcc-13

Comment (seiko2plus) [reply numpy/core/src/common/half.hpp:75]: IDK, why CI intel_spr_sde_test didn't trigger this error

Comment (seberg) [reply numpy/core/src/common/half.hpp:75]: Ah, the missing SPR test issue bit us.

**Comment by charris** [comment]
This fixes the build for me. Thanks Sayed.

File: numpy/core/src/common/half.hpp (hunk 1 above)
Comment (r-devulap) [reply numpy/core/src/common/half.hpp:75]: `NPY_HAVE_AVX512_SPR ` is enabled with gcc >= 12.x. My nightly job picked up this failure with gcc-12 as well. See https://github.com/intel/x86-simd-sort/actions/runs/4879269275/jobs/8705679224.

The `intel_spr_sde_test` is disabled currently because of an SDE bug. I think what we could do is enable this CI just to build with gcc-12 without running the tests in the SDE.

**Comment by charris** [comment]
Hmm, I suspect this has broken the clang wheel builds for Mac on Intel.
```
INFO: clang++: build/src.macosx-10.9-x86_64-3.9/numpy/core/src/npysort/simd_qsort_16bit.dispatch.avx512_spr.cpp
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: note: diagnostic msg:
```
See https://github.com/numpy/numpy/actions/runs/4885881750/jobs/8720521372.
