### ISSUE TITLE
NumPy fails to build on aarch64

### ISSUE THREAD

**Issue by jjhelmus** [numpy/numpy#11564]
The master branch currently fails to build on aarch64/ARMv8 with the following:

```
aarch64-linux-gnu-gcc: numpy/core/src/npymath/ieee754.c
In file included from numpy/core/src/private/npy_config.h:6:0,
                 from numpy/core/src/npymath/npy_math_common.h:8,
                 from numpy/core/src/npymath/ieee754.c.src:7:
numpy/core/include/numpy/npy_cpu.h:106:6: error: #error Unknown CPU, please report this to numpy maintainers with information about your platform (OS, CPU and compiler)
     #error Unknown CPU, please report this to numpy maintainers with \
      ^
In file included from numpy/core/src/private/npy_config.h:6:0,
                 from numpy/core/src/npymath/npy_math_common.h:8,
                 from numpy/core/src/npymath/ieee754.c.src:7:
numpy/core/include/numpy/npy_cpu.h:106:6: error: #error Unknown CPU, please report this to numpy maintainers with information about your platform (OS, CPU and compiler)
     #error Unknown CPU, please report this to numpy maintainers with \
      ^
error: Command "aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Inumpy/core/src/npymath -Inumpy/core/include -Inumpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python3.5m -Inumpy/core/src/private -Inumpy/core/src/npymath -Inumpy/core/src/private -Inumpy/core/src/npymath -Inumpy/core/src/private -Inumpy/core/src/npymath -c numpy/core/src/npymath/ieee754.c -o build/temp.linux-aarch64-3.5/numpy/core/src/npymath/ieee754.o -MMD -MF build/temp.linux-aarch64-3.5/numpy/core/src/npymath/ieee754.o.d" failed with exit status 1
```

I believe this is a result of the new detection logic introduced in #11016.  It seems as if `__arm__` and `__ARMEL__` may not be defined on some? aarch64 platforms.  Rather it may be necessary to use `__aarch64__` and `__AARCH64EL__`.

**Comment by charris** [comment]
What are you using for the build?

**Comment by jjhelmus** [comment]
[Scaleway](https://www.scaleway.com/) offers ARMv8 and ARMv7 cloud instances at very reasonable prices which I have been using for testing.  @ksunden has a Chromebook (An Acer Chromebook R13 perhaps?) that has a ARMv8 processor that was used to verify and debug this issue.  [Shippable](http://www.shippable.com/) recently [started offing free ARMv8 CI/CD](http://blog.shippable.com/shippable-arm-packet-deliver-native-ci-cd-for-arm-architecture) for open source projects.

**Comment by rgommers** [comment]
I'd be +1 for ARM CI. Is the Shippable offering fast enough? Would like to avoid long delay in CI starting/completing, this has been (or is) pretty annoying with AppVeyor. If that's an issue, then paying 3 euro/month for Scaleway is fine with me.

**Comment by jjhelmus** [comment]
On the machines I've been using for testing `__ARM_<BITS>BIT_STATE` are defined:

ARMv8:
```
~# lscpu
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
~# g++ -dM -E - </dev/null | egrep -i '(arm|neon|aarch)'
#define __ARM_SIZEOF_WCHAR_T 4
#define __ARM_FEATURE_UNALIGNED 1
#define __ARM_FEATURE_IDIV 1
#define __ARM_FP 14
#define __AARCH64_CMODEL_SMALL__ 1
#define __ARM_ALIGN_MAX_STACK_PWR 16
#define __ARM_SIZEOF_MINIMAL_ENUM 4
#define __ARM_ALIGN_MAX_PWR 28
#define __ARM_FP16_FORMAT_IEEE 1
#define __aarch64__ 1
#define __ARM_FP16_ARGS 1
#define __ARM_FEATURE_FMA 1
#define __ARM_64BIT_STATE 1
#define __ARM_ARCH_PROFILE 65
#define __ARM_PCS_AAPCS64 1
#define __AARCH64EL__ 1
#define __ARM_FEATURE_CLZ 1
#define __ARM_ARCH 8
#define __ARM_ARCH_8A 1
#define __ARM_NEON 1
#define __ARM_FEATURE_NUMERIC_MAXMIN 1
#define __ARM_ARCH_ISA_A64 1
```

ARMv7

```
~# lscpu 
Architecture:          armv7l
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
Model name:            ARMv7 Processor rev 2 (v7l)
CPU max MHz:           1333.0000
CPU min MHz:           666.5000
Hypervisor vendor:     (null)
Virtualization type:   full
~# g++ -dM -E - </dev/null | egrep -i '(arm|neon|aarch)'
#define __ARM_SIZEOF_WCHAR_T 4
#define __ARM_FEATURE_SAT 1
#define __ARM_ARCH_ISA_ARM 1
#define __ARMEL__ 1
#define __ARM_FEATURE_UNALIGNED 1
#define __ARM_FP 12
#define __ARM_ASM_SYNTAX_UNIFIED__ 1
#define __ARM_SIZEOF_MINIMAL_ENUM 4
#define __ARM_PCS_VFP 1
#define __ARM_FEATURE_LDREX 15
#define __ARM_FEATURE_QBIT 1
#define __ARM_ARCH_PROFILE 65
#define __ARM_32BIT_STATE 1
#define __ARM_FEATURE_CLZ 1
#define __ARM_ARCH_ISA_THUMB 2
#define __ARM_ARCH 7
#define __arm__ 1
#define __ARM_ARCH_7A__ 1
#define __ARM_FEATURE_SIMD32 1
#define __ARM_EABI__ 1
#define __ARM_FEATURE_DSP 1
```

**Comment by stuartarchibald** [comment]
@jjhelmus great, thanks, seems like they are consistently defined.
