### ISSUE TITLE
undefined reference to `PyCObject_Type'

### ISSUE THREAD

**Issue by aiyanxiao** [numpy/numpy#14516]
```
/usr/local/lib/python3.5/dist-packages/numpy/core/include/numpy/__multiarray_api.h:1488: undefined reference to `PyCObject_Type'
```

**Comment by charris** [comment]
Looks like it was compiled against Python 2.7. Where did you get NumPy?

**Comment by aiyanxiao** [comment]
> Looks like it was compiled against Python 2.7. Where did you get NumPy?

Thanks for your help.I want to set interface in c++ with Python 3.5, so I pip install numpy==1.15.2 in Python 3.5 of Ubuntu 16.04.I didn't know the reason why it can't work. I have also tried it in Python 2.7,which can compile rightly.However, I use the model is Python 3.5 in pytorch which can't work in Python 2.7.  So, could you help me to solve the problem?

**Comment by mattip** [comment]
You should be using a distribution like anaconda.com/downloads or a virtual environment. Using `sudo pip install ...` is not good practice since it overrides `apt install python-...`.

**Comment by aiyanxiao** [comment]
> You should be using a distribution like anaconda.com/downloads or a virtual environment. Using `sudo pip install ...` is not good practice since it overrides `apt install python-...`.

Thanks for your answer. I did it according to your suggest.But it still didn't work.  The CMakeLists.txt is as follow:
cmake_minimum_required(VERSION 2.8 FATAL_ERROR)
set( CMAKE_CXX_FLAGS "-std=c++11" )
project(Mat2PIL)

set(CMAKE_BUILD_TYPE DEBUG)
set(CMAKE_CXX_STANDARD 14)

set(OpenCV_DIR ~/opencv-2.4.11/build)
LIST(APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake_modules)
find_package(OpenCV 2.4.11 REQUIRED)


find_package(PythonLibs REQUIRED)
if (NOT PythonLibs_FOUND)
    message(FATAL_ERROR "PYTHON LIBS not found.")
else()
    message("PYTHON LIBS were found!")
    message("PYTHON LIBS DIRECTORY: " ${PYTHON_LIBRARY})
endif()

find_package(Boost REQUIRED COMPONENTS thread)
if(Boost_FOUND)
    message("Boost was found!")
    message("Boost Headers DIRECTORY: " ${Boost_INCLUDE_DIRS})
    message("Boost LIBS DIRECTORY: " ${Boost_LIBRARY_DIRS})
    message("Found Libraries: " ${Boost_LIBRARIES})
endif()

find_package(Eigen3  REQUIRED)
find_package(Pangolin REQUIRED)

set(PYTHON_INCLUDE_DIRS ${PYTHON_INCLUDE_DIRS} /home/cvg/anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/numpy/core/include/numpy)
#set(PYTHON_INCLUDE_DIRS ${PYTHON_INCLUDE_DIRS} /usr/local/lib/python3.5/dist-packages/torch/lib/include/torch)

include_directories(
${PROJECT_SOURCE_DIR}
${PROJECT_SOURCE_DIR}/include
${EIGEN3_INCLUDE_DIR}
${Pangolin_INCLUDE_DIRS}
/home/cvg/anaconda3/envs/pytorch1.0.0/include/python3.6m/
/home/cvg/anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/numpy/core/include/numpy/
#/usr/local/lib/python3.5/dist-packages/torch/lib/include/torch
${Boost_INCLUDE_DIRS}
)

set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/lib)

add_library(${PROJECT_NAME} SHARED
src/System.cc
src/Tracking.cc
src/LocalMapping.cc
src/LoopClosing.cc
src/ORBextractor.cc
src/ORBmatcher.cc
src/FrameDrawer.cc
src/Converter.cc
src/MapPoint.cc
src/KeyFrame.cc
src/Map.cc
src/MapDrawer.cc
src/Optimizer.cc
src/PnPsolver.cc
src/Frame.cc
src/KeyFrameDatabase.cc
src/Sim3Solver.cc
src/Initializer.cc
src/Viewer.cc
src/Conversion.cc
src/MaskNet.cc
src/Geometry.cc
)

target_link_libraries(${PROJECT_NAME} 
${OpenCV_LIBS}
${EIGEN3_LIBS}
${Pangolin_LIBRARIES}
${PROJECT_SOURCE_DIR}/Thirdparty/DBoW2/lib/libDBoW2.so
${PROJECT_SOURCE_DIR}/Thirdparty/g2o/lib/libg2o.so
/home/cvg/anaconda3/envs/pytorch1.0.0/lib/libpython3.6m.so    
${Boost_LIBRARIES}
)

add_executable(mat2ppil mat2ppil.cpp)
target_link_libraries(mat2ppil ${PROJECT_NAME})

However, it still occurred the error that is as follow:


[100%] Linking CXX executable mat2ppil
CMakeFiles/mat2ppil.dir/mat2ppil.cpp.o: In function `_import_array':
/home/cvg/anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/numpy/core/include/numpy/__multiarray_api.h:1487: undefined reference to `PyCObject_Type'
/home/cvg/anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/numpy/core/include/numpy/__multiarray_api.h:1492: undefined reference to `PyCObject_AsVoidPtr'
../lib/libMat2PIL.so: undefined reference to `PyInstance_New'
collect2: error: ld returned 1 exit status
CMakeFiles/mat2ppil.dir/build.make:132: recipe for target 'mat2ppil' failed
make[2]: *** [mat2ppil] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mat2ppil.dir/all' failed
make[1]: *** [CMakeFiles/mat2ppil.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
*** Failure: Exit code 2 ***

**Comment by eric-wieser** [comment]
`PyInstance_New` was removed in python 3 - it looks like `libMat2PIL` needs updating to work with python 3

**Comment by seberg** [comment]
I am going to close this, the issue is an incorrect build of a downstream library (or the use of a numpy build against a different python version).
