### PR TITLE
BUG: import full module path in npy_load_module

### LINKED ISSUE #8147: Configuration.add_subpackage fails on Python 3.4
Using numpy 1.11.2 and Python 3.4, trying to run a `setupy.py` script which uses subpackage using numpy.distutil fails when `importlib.machinery` cannot be found in the `npy_load_module` function.

For example using the following `setup.py` and `foo/setup.py` scripts:

``` Python
# setup.py
from numpy.distutils.misc_util import Configuration
from numpy.distutils.core import setup

def configuration():
    config = Configuration(None, '', None)
    config.add_subpackage('foo')
    return config

setup(configuration=configuration)
```

``` Python
# foo/setup.py
def configuration(parent_package='', top_path=None):
    from numpy.distutils.misc_util import Configuration
    config = Configuration('foo', parent_package, top_path)
    return config
```

Attempting to build the package:

```
$ python setup.py build_ext -i
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    setup(configuration=configuration)
  File "/Users/jhelmus/anaconda/envs/py34/lib/python3.4/site-packages/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "setup.py", line 7, in configuration
    config.add_subpackage('foo')
  File "/Users/jhelmus/anaconda/envs/py34/lib/python3.4/site-packages/numpy/distutils/misc_util.py", line 1000, in add_subpackage
    caller_level = 2)
  File "/Users/jhelmus/anaconda/envs/py34/lib/python3.4/site-packages/numpy/distutils/misc_util.py", line 969, in get_subpackage
    caller_level = caller_level + 1)
  File "/Users/jhelmus/anaconda/envs/py34/lib/python3.4/site-packages/numpy/distutils/misc_util.py", line 882, in _get_configuration_from_setup_py
    ('.py', 'U', 1))
  File "/Users/jhelmus/anaconda/envs/py34/lib/python3.4/site-packages/numpy/compat/py3k.py", line 112, in npy_load_module
    return importlib.machinery.SourceFileLoader(name, fn).load_module()
AttributeError: 'module' object has no attribute 'machinery'
```

This works in Python 3.5 and 2.7 and with earlier versions of NumPy prior to the addition of `npy_load_module`.  

This bug can likely be fixed by adding `import importlib` to the `npy_load_module`.  I will submit a PR shortly.

A workaround is to `import importlib.machinery` somewhere in the root `setup.py` file.

### PR DESCRIPTION
**Pull request by jjhelmus**
Use the full module path when importing importlib.machinery for use in the
npy_load_module function. Just importing importlib is not sufficient in certain
cases, for example Python 3.4.

closes #8147

### CODE REVIEW

**Comment by njsmith** [comment]
Change looks good but can we get a test?

**Comment by jjhelmus** [comment]
Was thinking about the following as a test:

``` Python
def test_npy_load_module_py34():
    with tempdir(prefix="numpy_test_compat_") as folder:
        filename = join(folder, 'example.py')
        with open(filename, 'w') as f:
            f.write("magic_number = 42")
        example = npy_load_module('example', filename)
        assert_(example.magic_number == 42)
```

The issue is that this passes with or without the proposed fix.  Outside of the test suite the assert will fail without the fix but inside the test suite it always passes.

**Comment by jjhelmus** [comment]
Fun, `machinery` is not in the importlib module namespace if imported alone, but it is after nose is imported:

```
Python 3.4.5 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:47:57)
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib
>>> dir(importlib)
['_RELOADING', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__import__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_bootstrap', '_imp', '_r_long', '_w_long', 'find_loader', 'import_module', 'invalidate_caches', 'reload', 'sys', 'types', 'warnings']
>>> import nose
>>> dir(importlib)
['_RELOADING', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__import__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_bootstrap', '_imp', '_r_long', '_w_long', 'find_loader', 'import_module', 'invalidate_caches', 'machinery', 'reload', 'sys', 'types', 'util', 'warnings']
```

I'm at a loss on how write a test that changes from pass to fail with the proposed modification.

**Comment by njsmith** [comment]
Ugh, wow.

Hail mary: `subprocess.run([sys.executable, "-c", "import numpy; numpy.npy_load_module(..."])`?

Or if it's not doable we can skip it.

**Comment by charris** [comment]
@njsmith I'm going to put this in, figuring out how to test it looks to be more trouble than it is worth.

**Comment by charris** [comment]
Thanks @jjhelmus .

**Comment by jakirkham** [comment]
Would this be backported to 1.11?
