### ISSUE TITLE
BUG(?): Can't build extension module on Windows with rtools 4.0 or with cibuildwheel

### ISSUE THREAD

**Issue by WarrenWeckesser** [numpy/numpy#24678]
### Describe the issue:

I'm trying to build and test [`ufunclab`](https://github.com/WarrenWeckesser/ufunclab) in github/actions on Windows using [rtools 4.0](https://cran.r-project.org/bin/windows/Rtools/rtools40.html) to install the compiler toolchain.  I use `meson-python` as the build system, and I'm using a much simplified version of SciPy's [`windows.yml`](https://github.com/scipy/scipy/blob/main/.github/workflows/windows.yml) to configure github/actions.  My file is [`tests.yml`](https://github.com/WarrenWeckesser/ufunclab/blob/main/.github/workflows/tests.yml); the Windows job starts at line 114.

My build works with 1.22.4. The problem occurs when I try to build with numpy 1.25.2.  I am running into two build issues on Windows:

* I get multiple occurrences of the warning

      Warning: corrupt .drectve at end of def file

  I think this is related to the closed issue https://github.com/numpy/numpy/issues/21629, but it is not clear to me how to fix the warning in my code. 
* The build fails because of "undefined reference to `feraiseexcept'". Here is the error message after my latest configuration tweak when I try to build :
  ```
    [38/125] Linking target ufunclab/_abs_squared.cp310-win_amd64.pyd
    FAILED: ufunclab/_abs_squared.cp310-win_amd64.pyd
    "c++"  -o ufunclab/_abs_squared.cp310-win_amd64.pyd ufunclab/_abs_squared.cp310-win_amd64.pyd.p/meson-generated_..__abs_squared.cxx.obj ufunclab/_abs_squared.cp310-win_amd64.pyd.p/meson-generated_.._abs_squared_concrete.cxx.obj "-Wl,--allow-shlib-undefined" "-Wl,-O1" "-shared" "-Wl,--start-group" "-Wl,--out-implib=ufunclab\_abs_squared.cp310-win_amd64.dll.a" "-Wl,--allow-multiple-definition" "-lm" "C:/hostedtoolcache/windows/Python/3.10.11/x64/lib/site-packages/numpy/core/include/../lib/npymath.lib" "C:\hostedtoolcache\windows\Python\3.10.11\x64\python310.dll" "-lkernel32" "-luser32" "-lgdi32" "-lwinspool" "-lshell32" "-lole32" "-loleaut32" "-luuid" "-lcomdlg32" "-ladvapi32" "-Wl,--end-group"
    Warning: corrupt .drectve at end of def file
    c:/rtools40/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/hostedtoolcache/windows/Python/3.10.11/x64/lib/site-packages/numpy/core/include/../lib/npymath.lib(build/temp.win-amd64-3.10/build/src.win-amd64-3.10/numpy/core/src/npymath/ieee754.obj):(.text$mn+0x6): undefined reference to `feraiseexcept'
    c:/rtools40/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/hostedtoolcache/windows/Python/3.10.11/x64/lib/site-packages/numpy/core/include/../lib/npymath.lib(build/temp.win-amd64-3.10/build/src.win-amd64-3.10/numpy/core/src/npymath/ieee754.obj):(.text$mn+0x6): undefined reference to `feraiseexcept'
    c:/rtools40/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/hostedtoolcache/windows/Python/3.10.11/x64/lib/site-packages/numpy/core/include/../lib/npymath.lib(build/temp.win-amd64-3.10/build/src.win-amd64-3.10/numpy/core/src/npymath/ieee754.obj):(.text$mn+0x6): undefined reference to `feraiseexcept'
    c:/rtools40/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/hostedtoolcache/windows/Python/3.10.11/x64/lib/site-packages/numpy/core/include/../lib/npymath.lib(build/temp.win-amd64-3.10/build/src.win-amd64-3.10/numpy/core/src/npymath/ieee754.obj):(.text$mn+0x6): undefined reference to `feraiseexcept'
  ```
  Is this problem familiar to anyone?

### Reproduce the code example:

```python
See above.
```

### Error message:

```shell
See above.
```

### Runtime information:

NumPy 1.25.2, Python 3.10.

The problem is occurring on the platform `windows-2019` running under github/actions with the toolchain provided by rtools 4.0 used to build my extension modules.

**Comment by charris** [comment]
I think you only need rtools 4.0.0 for 32 bit windows builds. Installing rtools can be tricky because it is preinstalled in github actions, see #23951 for how numpy does it.

**Comment by WarrenWeckesser** [comment]
Thanks @charris.  I created a separate github action ([`wheels.yml`](https://github.com/WarrenWeckesser/ufunclab/blob/main/.github/workflows/wheels.yml)) that uses cibuildwheel to build and test the project.  I still get the warnings and build failure:

```
    [35/125] Linking target ufunclab/_abs_squared.cp39-win_amd64.pyd
    FAILED: ufunclab/_abs_squared.cp39-win_amd64.pyd
    "c++"  -o ufunclab/_abs_squared.cp39-win_amd64.pyd ufunclab/_abs_squared.cp39-win_amd64.pyd.p/meson-generated_..__abs_squared.cxx.obj ufunclab/_abs_squared.cp39-win_amd64.pyd.p/meson-generated_.._abs_squared_concrete.cxx.obj "-Wl,--allow-shlib-undefined" "-Wl,-O1" "-shared" "-Wl,--start-group" "-Wl,--out-implib=ufunclab\_abs_squared.cp39-win_amd64.dll.a" "-Wl,--allow-multiple-definition" "-lm" "C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-ldncs2c5/overlay/Lib/site-packages/numpy/core/include/../lib/npymath.lib" "C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\python.3.9.13\tools\python39.dll" "-lkernel32" "-luser32" "-lgdi32" "-lwinspool" "-lshell32" "-lole32" "-loleaut32" "-luuid" "-lcomdlg32" "-ladvapi32" "-Wl,--end-group"
    Warning: corrupt .drectve at end of def file
    C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-ldncs2c5/overlay/Lib/site-packages/numpy/core/include/../lib/npymath.lib(build/temp.win-amd64-3.9/build/src.win-amd64-3.9/numpy/core/src/npymath/ieee754.obj):(.text$mn+0xd): undefined reference to `__imp_fetestexcept'
    C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-ldncs2c5/overlay/Lib/site-packages/numpy/core/include/../lib/npymath.lib(build/temp.win-amd64-3.9/build/src.win-amd64-3.9/numpy/core/src/npymath/ieee754.obj):(.text$mn+0x37): undefined reference to `__imp_feclearexcept'
    C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-ldncs2c5/overlay/Lib/site-packages/numpy/core/include/../lib/npymath.lib(build/temp.win-amd64-3.9/build/src.win-amd64-3.9/numpy/core/src/npymath/ieee754.obj):(.text$mn+0x10): undefined reference to `__imp_fetestexcept'
    C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-ldncs2c5/overlay/Lib/site-packages/numpy/core/include/../lib/npymath.lib(build/temp.win-amd64-3.9/build/src.win-amd64-3.9/numpy/core/src/npymath/ieee754.obj):(.text$mn+0x41): undefined reference to `__imp_feclearexcept'
    C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-ldncs2c5/overlay/Lib/site-packages/numpy/core/include/../lib/npymath.lib(build/temp.win-amd64-3.9/build/src.win-amd64-3.9/numpy/core/src/npymath/ieee754.obj):(.text$mn+0xb): undefined reference to `__imp_fetestexcept'
    C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-ldncs2c5/overlay/Lib/site-packages/numpy/core/include/../lib/npymath.lib(build/temp.win-amd64-3.9/build/src.win-amd64-3.9/numpy/core/src/npymath/ieee754.obj):(.text$mn+0x10): undefined reference to `__imp_fetestexcept'
    C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-ldncs2c5/overlay/Lib/site-packages/numpy/core/include/../lib/npymath.lib(build/temp.win-amd64-3.9/build/src.win-amd64-3.9/numpy/core/src/npymath/ieee754.obj):(.text$mn+0xd): undefined reference to `_dclass'
    C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-ldncs2c5/overlay/Lib/site-packages/numpy/core/include/../lib/npymath.lib(build/temp.win-amd64-3.9/build/src.win-amd64-3.9/numpy/core/src/npymath/ieee754.obj):(.text$mn+0xd): undefined reference to `_fdclass'
    C:/Users/runneradmin/AppData/Local/Temp/pip-build-env-ldncs2c5/overlay/Lib/site-packages/numpy/core/include/../lib/npymath.lib(build/temp.win-amd64-3.9/build/src.win-amd64-3.9/numpy/core/src/npymath/ieee754.obj):(.text$mn+0xd): undefined reference to `_dclass'
    collect2.exe: error: ld returned 1 exit status
```

**Comment by WarrenWeckesser** [comment]
The SciPy issue https://github.com/scipy/scipy/issues/16787 looks like it might be the same issue, and links in that issue point to the NumPy issues https://github.com/numpy/numpy/issues/20880 and https://github.com/numpy/numpy/issues/21629.

**Comment by rgommers** [comment]
> The SciPy file only builds with numpy 1.22.4

I don't think that that is the case. Maybe in just that file it is, however `pyproject.toml` contains `==1.23.2` pins for Python 3.11, and the wheel build for Python 3.12 are being done against numpy nightlies.

> Edit: A different extension module has many more undefined references--it looks like it is not finding any of the standard math library:

I think you need to link against `libm` like so: https://github.com/scipy/scipy/blob/00e47d73997ea8d8ef22937c6fd00e355a9a82e2/meson.build#L65-L71

Other question: do you really need to link against the `libnpymath` static library? I still want to get rid of it as soon as we can, due to exactly this type of problem.

**Comment by WarrenWeckesser** [comment]
>> The SciPy file only builds with numpy 1.22.4

> I don't think that that is the case. 

You're right, while several of the builds in that file have 1.22.4 hardcoded, not all of them do.  I edited my comment.

> I think you need to link against libm ...

I have tried that, and I currently add `-lm` to the `link_args` parameter of meson-python's `extension_module()` functions for any of my C extension modules.

One thing I noticed is that, in the linking command, meson put the argument `-lm` on the command line *before* the npymath library.  That won't work if my code doesn't explicitly reference functions from the math library but npymath does.  But I might be Using It Wrong, and may have misconfigured something.

> Other question: do you really need to link against the libnpymath static library? 

I'll do a more thorough audit soon and see how much I can replace npymath with C/C++ standard libs, but for now I'll just say I use several functions from npymath.
 
One function that I'm pretty sure I won't find in a compiler's standard library is `npy_half_to_float()` that converts from the type `npy_half` to C `float`; see @ngoldbaum's [comment](https://github.com/numpy/numpy/issues/20880#issuecomment-1612011687) regarding the half float type.  I support `float16` in a few ufuncs, and I'll probably expand support for the type over time.

**Comment by rgommers** [comment]
> One thing I noticed is that, in the linking command, meson put the argument `-lm` on the command line _before_ the npymath library. That won't work if my code doesn't explicitly reference functions from the math library but npymath does. But I might be Using It Wrong, and may have misconfigured something.

Ah, you should be able to reorder those arguments. Probably by making the `npymath_lib` target itself understand that it requires libm. We haven't noticed this in SciPy I think because in the few places where we still use libnpymath we're also using a ton of C99 functions.

If this doesn't resolve it, there may be a fundamental mismatch that we somehow didn't run into in SciPy. The correct answer is anyway "use MSVC" here I believe, since you don't have Fortran code. Using Mingw-w64 may or may not work, it's off-label usage and never a good idea unless you have no other choice.

**Comment by WarrenWeckesser** [comment]
> Probably by making the npymath_lib target itself understand that it requires libm.

You've already hit the limit of my meson knowledge.  I use some code copied from SciPy to get the numpy include path and then do

```
npymath_path = _incdir_numpy_abs / '..' / 'lib'
npymath_lib = cc.find_library('npymath', dirs: npymath_path)
```
I don't see any way to tell meson that `npymath` depends on the math library.

>  The correct answer is anyway "use MSVC" 

Doesn't cibuildwheel use MSVC?  The linking issue occurred in both the rtools-based build and in the github action that used cibuildwheel. The output shown in https://github.com/numpy/numpy/issues/24678#issuecomment-1712928114 is from the cibuildwheel log.

**Comment by rgommers** [comment]
> I don't see any way to tell meson that `npymath` depends on the math library.

I think the way to do it is to use [declare_dependency](https://mesonbuild.com/Reference-manual_functions.html#declare_dependency):
```meson
npymath_dep = declare_dependency(
    link_with: npymath_lib,
    link_args: m_dep,  # m_dep as in the scipy code linked in a comment higher up
)
```

> Doesn't cibuildwheel use MSVC? 

I browsed through your CI logs, but all the failing ones seem to use `gcc`. And the `corrupt .drectve` issue is Mingw-w64 specific I believe.

`cibuildwheel` does nothing to select a compiler. Instead, Meson auto-selects one if you don't force it to use a specific one through setting the `CC`/`CXX` env vars. GHA runner images have rtools pre-installed. The Meson compiler selection works like this:
- in general, it uses the first one it finds on the PATH,
- on Windows, MSVC is special in that it's typically not on the PATH and even if it is, that is not enough - you must activate it through something like `vcvarsall.bat` (thanks Microsoft ...)
- Meson has one special rule: if no compilers are found on the PATH, it will auto-detect and activate MSVC

GitHub Actions images are full of junk, even broken compilers or `link.exe`. So you'll need to to do something to make it use MSVC. The NumPy `cibuildwheel` config in `pyproject.toml` should be instructive. In particular, the lines:
```toml
[tool.cibuildwheel.windows]
config-settings = "setup-args=--vsenv"
```
The `--vsenv` gets passes to `meson setup` that way, and that is what activates MSVC.

**Comment by WarrenWeckesser** [comment]
FYI: To build with MSVC in github actions, I switched to using the action [`ilammy/msvc-dev-cmd`](https://github.com/ilammy/msvc-dev-cmd).  After updating the code to work around MSVC's lack of support for C99 complex types, I was able to build the package and run the tests in a github action.

I don't think there is anything actionable here for numpy, so I'm closing this issue.
