### ISSUE TITLE
macOSX / clang compile fails with undefined locale identifiers

### ISSUE THREAD

**Issue by matthew-brett** [numpy/numpy#8693]
macOSX build now failing with undefined locale identifiiers, after merge of #7997 :

```
clang: numpy/core/src/multiarray/numpyos.c
numpy/core/src/multiarray/numpyos.c:518:5: error: use of undeclared identifier 'locale_t'
    locale_t clocale;
```

https://travis-ci.org/MacPython/numpy-wheels/jobs/205229905#L3775

Errors result from merge of https://github.com/numpy/numpy/pull/7997 - commit 23ac8554b builds (pre-merge), commit 7bc881d05 breaks (the merge commit).

@juliantaylor - any thoughts?

**Comment by juliantaylor** [comment]
the pr doesn't have any changes that should cause this.
how is HAVE_STRTOLD_L in the config.h of the build folder defined in the working and not working commit? make sure to clean the build folder before each build

**Comment by juliantaylor** [comment]
ah I see the problem, a missing comma ...
