### PR TITLE
MAINT: Match arguments of constant in `isless()`

### PR DESCRIPTION
**Pull request by juztamau5**
## Description

This is a cleanup commit broken out from https://github.com/numpy/numpy/pull/22545. When compiling with g++, argument types can't be deduced. An explicit cast solves that.

## How has this been tested?

Before the patch, on g++:

```
npy_math_internal.h.src:570:24: error: no matching function for call to 'isless(npy_float&, int)'
  570 |         if (isless(b, 0) != isless(mod, 0)) {
      |                  
```

After the patch, compile-tested with gcc and g++. I also ran the following code in my RISC-V VM:

```python
import numpy as np
print(np.sqrt(2))
```

output:

```
1.4142135623730951
```

### CODE REVIEW

**Comment by seberg** [comment]
Thanks @juztamau5.  Not sure it matters, but can't hurt and maybe it is better even in C99.
