### PR TITLE
BUG: Handle ``iso_c_type`` mappings more consistently

### LINKED ISSUE #25207: BUG: c2capi_map entries missing for iso_c_binding in f2py
### Describe the issue:

In https://github.com/numpy/numpy/pull/24555 the implementation of f2cmap was supplemented by definitions from iso_c_binding, however, due to an oversight there are no corresponding c2capi_map entries which results in `KeyError` during an f2py run.

### Reproduce the code example:

```python
subroutine add(A, B, C, N)
   use iso_c_binding, only: c_int64_t
   implicit none
   integer(c_int64_t), intent(in) :: A(*)
   integer(c_int64_t), intent(in) :: B(*)
   integer(c_int64_t), intent(out) :: C(*)
   integer, intent(in) :: N
   integer :: j

   do j = 1, N
      C(j) = A(j)+B(j)
   end do
end subroutine
```

### Error message:

```shell
$ python3 -m numpy.f2py -m add add.f90
Reading fortran codes...
        Reading file 'add.f90' (format:free)
Post-processing...
        Block: add
                        Block: add
In: :add:add.f90:add
get_useparameters: no module iso_c_binding info used by add
Applying post-processing hooks...
  character_backward_compatibility_hook
Post-processing (stage 2)...
Building modules...
    Building module "add"...
    Generating possibly empty wrappers"
    Maybe empty "add-f2pywrappers.f"
        Constructing wrapper function "add"...
getarrdims:warning: assumed shape array, using 0 instead of '*'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib64/python3.12/site-packages/numpy/f2py/__main__.py", line 5, in <module>
    main()
  File "/usr/local/lib64/python3.12/site-packages/numpy/f2py/f2py2e.py", line 734, in main
    run_main(sys.argv[1:])
  File "/usr/local/lib64/python3.12/site-packages/numpy/f2py/f2py2e.py", line 496, in run_main
    ret = buildmodules(postlist)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib64/python3.12/site-packages/numpy/f2py/f2py2e.py", line 418, in buildmodules
    dict_append(ret[name], rules.buildmodule(module, um))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib64/python3.12/site-packages/numpy/f2py/rules.py", line 1298, in buildmodule
    api, wrap = buildapi(nb)
                ^^^^^^^^^^^^
  File "/usr/local/lib64/python3.12/site-packages/numpy/f2py/rules.py", line 1476, in buildapi
    vrd = capi_maps.sign2map(a, var[a])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib64/python3.12/site-packages/numpy/f2py/capi_maps.py", line 602, in sign2map
    ret['pydocsign'], ret['pydocsignout'] = getpydocsign(a, var)
                                            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib64/python3.12/site-packages/numpy/f2py/capi_maps.py", line 410, in getpydocsign
    c2pycode_map[
KeyError: 'int64_t'
```

### Runtime information:

```python
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.26.2
3.12.0 (main, Oct  2 2023, 00:00:00) [GCC 13.2.1 20230918 (Red Hat 13.2.1-3)]
>>> print(numpy.show_runtime())
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'numpy_version': '1.26.2',
  'python': '3.12.0 (main, Oct  2 2023, 00:00:00) [GCC 13.2.1 20230918 (Red '
            'Hat 13.2.1-3)]',
  'uname': uname_result(system='Linux', node='0794a3b936a4', release='5.15.0-78-generic', version='#85~20.04.1-Ubuntu SMP Mon Jul 17 09:42:39 UTC 2023', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX'],
                      'not_found': ['AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]
None
```

### Context for the issue:

Workaround: Create a `.f2py_f2cmap` with the contents
```
{'integer':{'c_int64_t':'long_long'}}
```

### PR DESCRIPTION
**Pull request by HaoZeke**
Closes #25207. This one could use a backport. Needs:
- [x] Scoping TODOs (can't rewrite the entire `cfuncs` here)
- [x] Tests
- [x] Check that SciPy builds

As discussed below, there were basically two deficiencies:
- Type maps were not propagated
- Fortran types (`iso_c_binding`) were mapped to ignored C types
  - This is the default behavior, but is silent and the maps are done to basic (lowest precision) corresponding types

This PR fixes (pragmatically) both these deficiences, for the first problem, the fix is a simple refactor and cleanup.

The second issue is a little trickier. For now, the pragmatic solution (as done by users anyway) is to map the `iso_c_binding` kinds to supported `f2py` types, i.e. to one of:

```python
c2py_map = {'double': 'float',
            'float': 'float',                          # forced casting
            'long_double': 'float',                    # forced casting
            'char': 'int',                             # forced casting
            'signed_char': 'int',                      # forced casting
            'unsigned_char': 'int',                    # forced casting
            'short': 'int',                            # forced casting
            'unsigned_short': 'int',                   # forced casting
            'int': 'int',                              # forced casting
            'long': 'int',
            'long_long': 'long',
            'unsigned': 'int',                         # forced casting
            'complex_float': 'complex',                # forced casting
            'complex_double': 'complex',
            'complex_long_double': 'complex',          # forced casting
            'string': 'string',
            'character': 'bytes',
            }
```

Pending a more complete overhaul of the generated bindings (tracked in #25229, which @Pranavchiku is also looking into) this is the optimal bugfix for #25207.

### CODE REVIEW

**Comment by mattip** [comment]
I'm not sure I can review this without some context.

**Comment by HaoZeke** [comment]
> I'm not sure I can review this without some context.

Sorry, so the reported issue is that as currently implemented, the `iso_c_binding` types introduced in #24555 are not handled the same way as manually adding `.f2cmap` files. So this PR fixes that, instead of just merging the type dictionaries, the mapping is considered to be the same as if the user had provided it in a `.f2cmap` file.

I will leave comments in the code.

File: numpy/f2py/auxfuncs.py [hunk 1]
```diff
@@ -893,28 +893,6 @@ def applyrules(rules, d, var={}):
...
-    for key, value in dict2.items():
-        if key in merged_dict:
-            if isinstance(merged_dict[key], dict) and isinstance(value, dict):
-                merged_dict[key] = deep_merge(merged_dict[key], value)
-            else:
-                merged_dict[key] = value
-        else:
-            merged_dict[key] = value
-    return merged_dict
-
```
Comment (HaoZeke) [inline numpy/f2py/auxfuncs.py:917]: No longer required since it is handled in `process_f2cmap_dict`

File: numpy/f2py/capi_maps.py [hunk 2]
```diff
@@ -151,29 +155,11 @@ def load_f2cmap_file(f2cmap_file):
...
-                        outmess(
-                            "\tWarning: redefinition of {'%s':{'%s':'%s'->'%s'}}\n" % (k, k1, f2cmap_all[k][k1], d[k][k1]))
-                    f2cmap_all[k][k1] = d[k][k1]
-                    outmess('\tMapping "%s(kind=%s)" to "%s"\n' %
-                            (k, k1, d[k][k1]))
-                    f2cmap_mapped.append(d[k][k1])
-                else:
-                    errmess("\tIgnoring map {'%s':{'%s':'%s'}}: '%s' must be in %s\n" % (
-                        k, k1, d[k][k1], d[k][k1], list(c2py_map.keys())))
+        f2cmap_all, f2cmap_mapped = process_f2cmap_dict(f2cmap_all, d, c2py_map, True)
```
Comment (HaoZeke) [inline numpy/f2py/capi_maps.py:158]: This section is used to handle user provided `f2cmap` files, now refactored into a function, `process_f2cmap_dict` which is also used for the `iso_c_binding` types.

File: numpy/f2py/capi_maps.py [hunk 3]
```diff
@@ -126,13 +126,17 @@
               'byte': {'': 'char'},
               }
 
-f2cmap_all = deep_merge(f2cmap_all, iso_c_binding_map)
+# Add ISO_C handling
+c2pycode_map.update(isoc_c2pycode_map)
+c2py_map.update(iso_c2py_map)
+f2cmap_all, _ = process_f2cmap_dict(f2cmap_all, iso_c_binding_map, c2py_map)
+# End ISO_C handling
 f2cmap_default = copy.deepcopy(f2cmap_all)
```
Comment (HaoZeke) [inline numpy/f2py/capi_maps.py:134]: The problem with the old handling is that updating the `f2cmap_all` doesn't preserve / update the mapping basically.

File: numpy/f2py/auxfuncs.py [hunk 4]
```diff
@@ -939,3 +917,72 @@ def getuseblocks(pymod):
...
+                    outmess('\tMapping "%s(kind=%s)" to "%s"\n' % (k, k1, v1))
+                f2cmap_mapped.append(v1)
+            else:
+                if verbose:
+                    errmess(
+                        "\tIgnoring map {'%s':{'%s':'%s'}}: '%s' must be in %s\n"
+                        % (k, k1, v1, v1, list(c2py_map.keys()))
+                    )
+
+    return f2cmap_all, f2cmap_mapped
```
Comment (HaoZeke) [inline numpy/f2py/auxfuncs.py:988]: The return here is key, previously only the f2cmap dictionary was being updated, now we ensure the mapped types are tracked as well.

File: numpy/f2py/capi_maps.py (hunk 2 above)
Comment (HaoZeke) [reply numpy/f2py/capi_maps.py:158]: Essentially, the bug in #24555 was that I didn't update `f2cmap_mapped`.

File: numpy/f2py/_isocbind.py [hunk 5]
```diff
@@ -51,6 +51,75 @@
...
+#     'float': 'float',
+#     'double': 'float',              # forced casting
+#     'long double': 'float',         # forced casting
+#     'float _Complex': 'complex',     # forced casting
+#     'double _Complex': 'complex',
+#     'long double _Complex': 'complex', # forced casting
+#     '_Bool': 'bool',
+#     'char': 'bytes',                  # approx Python bytes
+# }
+
```
Comment (HaoZeke) [inline numpy/f2py/_isocbind.py]: This whole section is a precursor to the discussion in #25229, but essentially, the question is about converting correctly, currently the mapping is just for kinds, i.e.  to map types from Fortran to C. Ideally it should also correctly handle them at the Python-C interface level, but that would be too much to cover here....


In fact, since the current bugfix is to fix the missing handling of `f2cmap_mapped`, this section isn't needed for this PR.

**Comment by HaoZeke** [comment]
Actually making this a draft to check the subroutine mentioned in the original issue.

File: numpy/f2py/_isocbind.py [hunk 6]
```diff
@@ -9,48 +9,53 @@
...
-        'c_int_fast32_t': 'int_fast32_t',
-        'c_int_fast64_t': 'int_fast64_t',
-        'c_intmax_t': 'intmax_t',
-        'c_intptr_t': 'intptr_t',
-        'c_ptrdiff_t': 'intptr_t',
+        'c_short': 'short',  # 'short' <=> 'int' for now
+        'c_long': 'long',  # 'long' <=> 'int' for now
+        'c_long_long': 'long_long',
+        'c_signed_char': 'signed_char',
+        'c_size_t': 'unsigned',  # size_t <=> 'unsigned' for now
```
Comment (HaoZeke) [inline numpy/f2py/_isocbind.py:20]: What's going on here is that the original PR was overly optimistic. F2PY can only support maps which are defined as part of the `c2py` keys. So for now, this performs forced casting to get around that.

Eventually, the various maps in `capi_maps` will be updated to get more correct bindings #25229. However, for now this is exactly the handling done typically at the user end via the `f2cmap` files.

**Comment by HaoZeke** [comment]
@mattip, let me know if this is clearer now :)

**Comment by HaoZeke** [comment]
> I have a potential fix for #25229 ready, do you wish me to open a PR or wait to get this merged?

We should wait for this to get merged, but feel free to open a draft PR, we can start iterating over it.

**Comment by HaoZeke** [comment]
@mattip does the extended rationale make sense?

**Comment by mattip** [comment]
Let's try this, hoepfully we will get some end-user feedback before the release.

Thanks @HaoZeke
