### PR TITLE
MAINT, CI: Update Ubuntu 18.04 to Ubuntu 20.04

### PR DESCRIPTION
**Pull request by charris**
Github actions will drop support for 18.04 April 1, 2023. There are now sporadic test cancelations due to warning brownouts, and the NumPy 1.24.x release will overlap that date, so increase the Ubuntu version.

The main change here is that there is no support for gcc-6 in Ubuntu 20.04, so testing with that version is dropped.

### CODE REVIEW

**Comment by charris** [comment]
Hmm, build error running "full" on azure:
```
numpy/core/src/multiarray/einsum_sumprod.c.src:1264:1: internal compiler error: in coverage_begin_function, at coverage.c:656
```

**Comment by charris** [comment]
Coverage fails in Ubuntu 20.04, but works in 22.04. Unfortunately, there are a lot of error like this:
```
numpy/core/src/multiarray/nditer_constr.c:2004:32: error: writing 8 bytes into a region of size 0 [-Werror=stringop-overflow=]
```
See https://github.com/numpy/numpy/actions/runs/3474938876/jobs/5808717885 for more. The `-Werror=stringop-overflow` option seems to be new with that version (new in gcc-10),  IIRC, we used to get warnings., In any case, we should probably fix those warnings. For now, I'm just going to disable the coverage option.

**Comment by seberg** [comment]
OK, lets put this in, thanks Chuck.  Was there something to followup on if the warning fixes work out?
