### ISSUE TITLE
numpy.load cannot read from tar archive in python3 ('_FileInFile' object has no attribute 'fileno')

### ISSUE THREAD

**Issue by dietmar** [numpy/numpy#7989]
I would like to `numpy.load` an ndarray from a file within a tar archive, without extracting to disk, in Python3.

```python
import os
import numpy
import tarfile

# create a test tar archive
a = numpy.random.rand(10, 4)
numpy.save('a.npy', a)
with open('foo.txt', 'w') as f:
    f.write('hey\nho\n')
t = tarfile.open('abc.tar', 'w')
t.add('a.npy')
t.add('foo.txt')
t.close()
del t, a
os.remove('a.npy')
os.remove('foo.txt')

# -----

t = tarfile.open('abc.tar', 'r')
a = numpy.load(t.extractfile('a.npy'))
```

The above code snippet works fine in Python 2.7.12 with numpy 1.11.1, but fails in Python 3.5.2 with numpy 1.11.1 (Debian Linux):
```
Traceback (most recent call last):
  File "loadtest.py", line 21, in <module>
    a = numpy.load(t.extractfile('a.npy'))
  File "[...]/lib/python3.5/site-packages/numpy/lib/npyio.py", line 406, in load
    pickle_kwargs=pickle_kwargs)
  File "[...]/lib/python3.5/site-packages/numpy/lib/format.py", line 648, in read_array
    array = numpy.fromfile(fp, dtype=dtype, count=count)
AttributeError: '_FileInFile' object has no attribute 'fileno'
```

Am I doing something wrong? [The numpy docs](http://docs.scipy.org/doc/numpy/reference/generated/numpy.load.html) say that I can pass a file-like object to `numpy.load`, which must support the `seek()` and `read()` methods, which the `io.BufferedReader` I receive from [TarFile.extractfile()](https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.extractfile) does.

**Comment by con-f-use** [comment]
I'm having the same issue. Any fix?

**Comment by dmitriy-serdyuk** [comment]
A hack to solve this is
```python
array_file = BytesIO()
array_file.write(t.extractfile('a.npy').read())
array_file.seek(0)
numpy.load(array_file)
```

**Comment by dietmar** [comment]
@dmitriy-serdyuk Well, if you have `a.npy` as a regular file, then you can just

```
a = numpy.load('a.npy')
```

But the whole point of this issue is when you *don't* have `a.npy` as a regular file, but inside of a `tar` archive.

**Comment by dietmar** [comment]
@dmitriy-serdyuk you're right, thanks for this workaround.

**Comment by Guilouf** [comment]
Rather than use this hack, try `numpy.frombuffer`, here an example of extracting 16bits integers:

```python
t = tarfile.open('abc.tar', 'rb')
extracted = t.extractfile('file.bin')
array = np.frombuffer(extracted.read(), dtype='<u2')
```

**Comment by dietmar** [comment]
@Guilouf in contrast to the other hack, your hack does not work with data stored using `numpy.save`, (which stores the dtype and also the array shape in addition to the numbers), but thanks for your suggestion.

**Comment by enricozb** [comment]
@dmitriy-serdyuk 

This loads the file contents to ram temporarily right? Because I have a 6.6 GB numpy npy file, which is too large to read to ram safely... I wish there was a way to read from a .tar file properly.

**Comment by dmitriy-serdyuk** [comment]
@enricozb I haven't tested this carefully, but it should load only one npy file from your tar. Make sure that you remove old `BytesIO` objects.
