### ISSUE TITLE
BUG: main fails to build — undefined function PyTuple_FromArray in ufunc_object.c

### ISSUE THREAD

**Issue by Mohataseem89** [numpy/numpy#31803]
### Describe the issue:

`main` currently fails to compile with GCC due to calls to `PyTuple_FromArray`,
a function that does not appear to be defined anywhere in the NumPy codebase
or in the CPython C API (the closest real API is `PyTuple_Pack`).

This was introduced by commit 45f7d0df718 (March 4, 2026), which added several
call sites to `PyTuple_FromArray` in `ufunc_object.c` and `real_imag_ufuncs.cpp`,
but the function itself was never defined.

I confirmed via `grep -rn "PyTuple_FromArray"` across `numpy/_core/src/` and
`numpy/_core/include/` that the function is called but never defined anywhere.

All call sites affected:
- numpy/_core/src/umath/ufunc_object.c:1409
- numpy/_core/src/umath/ufunc_object.c:3548
- numpy/_core/src/umath/ufunc_object.c:3704
- numpy/_core/src/umath/ufunc_object.c:3721
- numpy/_core/src/umath/ufunc_object.c:3741
- numpy/_core/src/umath/ufunc_object.c:3757
- numpy/_core/src/umath/ufunc_object.c:6569
- numpy/_core/src/umath/real_imag_ufuncs.cpp:211
- numpy/_core/src/umath/real_imag_ufuncs.cpp:242

### Reproduce the code example:

```python
git clone https://github.com/numpy/numpy.git
cd numpy
git submodule update --init
python3 -m venv .venv
source .venv/bin/activate
pip install spin meson meson-python ninja cython
spin build
```

### Error message:

```shell
../numpy/_core/src/umath/ufunc_object.c: In function '_parse_axes_arg':
../numpy/_core/src/umath/ufunc_object.c:1409:29: error: implicit declaration of
function 'PyTuple_FromArray'; did you mean 'PyArray_FromArray'?
[-Wimplicit-function-declaration]
 1409 |             op_axes_tuple = PyTuple_FromArray(&op_axes_tuple, 1);
      |                             ^~~~~~~~~~~~~~~~~
../numpy/_core/src/umath/ufunc_object.c:1409:27: error: assignment to 'PyObject *'
{aka 'struct _object *'} from 'int' makes pointer from integer without a cast
[-Wint-conversion]
ninja: build stopped: subcommand failed.
```

### Python and NumPy Versions:

numpy version: main @ 9721c24ba8 (build fails before import is possible)
Python 3.12.13 (main, ...) [GCC 15.2.0]

### Runtime Environment:

N/A — build fails before numpy can be imported, so numpy.show_runtime() cannot be run.

### How does this issue affect you or how did you find it:

Found while building `main` locally in a GitHub Codespace to test an unrelated
PR (#31796, fixing str_/bytes_ scalar indexing). The unrelated build failure
blocks compilation entirely for anyone building from a fresh clone of `main`,
and is also causing widespread CI failures (Linux, macOS, Windows, sanitizers,
wheel builders) on unrelated PRs.

**Comment by Mohataseem89** [comment]
Found while testing PR #31796 (unrelated change — str_/bytes_ scalar indexing fix).
Mentioning here in case useful context for verifying CI on that PR once this is fixed.

**Comment by WarrenWeckesser** [comment]
The function `PyTuple_FromArray` will be defined in the file `pythoncapi_compat.h` in the git submodule `numpy/_core/src/common/pythoncapi-compat`.  You should be able to see the file after you run `git submodule update --init`.

**Comment by ngoldbaum** [comment]
As Warren pointed out, this is happening because you don't have all the git submodules checked out in your clone of the repo.
