### ISSUE TITLE
BUG: Build of 2.2.2 fails only on ppc64le.

### ISSUE THREAD

**Issue by limburgher** [numpy/numpy#28220]
### Describe the issue:

https://kojipkgs.fedoraproject.org//work/tasks/6604/128376604/build.log

Worked on 2.2.1

### Reproduce the code example:

```python
Build issue
```

### Error message:

```shell

```

### Python and NumPy Versions:

Python 3.13, numpy 2.2.2

**Comment by mattip** [comment]
In the future, please provide more context when reporting an issue so we know what is going on. Digging into the log, this seems like a failure with Highway on some powerpc cpu

<details>

```
highway_qsort_16bit.dispatch.cpp
  In file included from ../numpy/_core/src/highway/hwy/highway.h:602,
                   from ../numpy/_core/src/npysort/highway_qsort.hpp:4,
                   from ../numpy/_core/src/npysort/highway_qsort_16bit.dispatch.cpp:1:
  ../numpy/_core/src/highway/hwy/ops/ppc_vsx-inl.h: In function ‘hwy::N_PPC8::VFromD<D> hwy::N_PPC8::PromoteTo(D, VFromD<typename D::Rebind<float> >)’:
  ../numpy/_core/src/highway/hwy/ops/ppc_vsx-inl.h:3713:33: error: there are no arguments to ‘__builtin_vsx_xvcvspsxds’ that depend on a template parameter, so a declaration of ‘__builtin_vsx_xvcvspsxds’ must be available [-Wtemplate-body]
   3713 |   return VFromD<decltype(di64)>{__builtin_vsx_xvcvspsxds(raw_v)};
        |                                 ^~~~~~~~~~~~~~~~~~~~~~~~
  ../numpy/_core/src/highway/hwy/ops/ppc_vsx-inl.h:3713:33: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
  ../numpy/_core/src/highway/hwy/ops/ppc_vsx-inl.h: In function ‘hwy::N_PPC8::VFromD<D> hwy::N_PPC8::PromoteTo(D, VFromD<typename D::Rebind<float> >)’:
  ../numpy/_core/src/highway/hwy/ops/ppc_vsx-inl.h:3727:7: error: there are no arguments to ‘__builtin_vsx_xvcvspuxds’ that depend on a template parameter, so a declaration of ‘__builtin_vsx_xvcvspuxds’ must be available [-Wtemplate-body]
   3727 |       __builtin_vsx_xvcvspuxds(raw_v))};
        |       ^~~~~~~~~~~~~~~~~~~~~~~~
  ../numpy/_core/src/highway/hwy/ops/ppc_vsx-inl.h: In function ‘hwy::N_PPC8::VFromD<D> hwy::N_PPC8::PromoteUpperTo(D, Vec128<float>)’:
  ../numpy/_core/src/highway/hwy/ops/ppc_vsx-inl.h:3837:33: error: there are no arguments to ‘__builtin_vsx_xvcvspsxds’ that depend on a template parameter, so a declaration of ‘__builtin_vsx_xvcvspsxds’ must be available [-Wtemplate-body]
   3837 |   return VFromD<decltype(di64)>{__builtin_vsx_xvcvspsxds(raw_v)};
        |                                 ^~~~~~~~~~~~~~~~~~~~~~~~
  ../numpy/_core/src/highway/hwy/ops/ppc_vsx-inl.h: In function ‘hwy::N_PPC8::VFromD<D> hwy::N_PPC8::PromoteUpperTo(D, Vec128<float>)’:
  ../numpy/_core/src/highway/hwy/ops/ppc_vsx-inl.h:3852:7: error: there are no arguments to ‘__builtin_vsx_xvcvspuxds’ that depend on a template parameter, so a declaration of ‘__builtin_vsx_xvcvspuxds’ must be available [-Wtemplate-body]
   3852 |       __builtin_vsx_xvcvspuxds(raw_v))};
```

</details>

**Comment by limburgher** [comment]
Noted. I wasn't sure what would be relevant. Happy to help testing patches.

**Comment by r-devulap** [comment]
It is being built with g++ (gcc 15.0.1 "g++ (GCC) 15.0.1 20250114 (Red Hat 15.0.1-0)") which doesn't have an official release yet and is still in [development](https://gcc.gnu.org/pipermail/gcc/2025-January/245377.html). @jan-wassenberg thoughts?

**Comment by r-devulap** [comment]
Never mind, looks like this was already resolved in https://github.com/google/highway/issues/2443. Pulling in latest highway should fix this.

**Comment by limburgher** [comment]
Thank you, that works!

**Comment by jan-wassenberg** [comment]
👍  Yes indeed, it seems GCC removed an intrinsic. Not sure why that was considered desirable. We were able to work around it, so all good.
